import {uid,clone,findActor} from './core.js';
import {TRAVEL_MODES,JOURNEY_STAGES,CAREER_TYPES,SERVICE_PROFILES,EXIT_BASES,serviceFor} from './campaign-data.js';
import {activeJourney,journeyBlockers} from './campaign.js';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(text,action,data='')=>`<button type="button" class="vh-button" data-action="${action}" ${data}>${text}</button>`;
const field=(label,name,value,type='text')=>`<label class="vh-field">${e(label)}<input name="${name}" type="${type}" value="${e(value)}"></label>`;
const area=(label,name,value)=>`<label class="vh-field">${e(label)}<textarea name="${name}" rows="3">${e(value)}</textarea></label>`;
const check=(label,name,checked)=>`<label class="vh-check"><input type="checkbox" name="${name}" ${checked?'checked':''}>${e(label)}</label>`;
const select=(label,name,pairs,value)=>`<label class="vh-field">${e(label)}<select name="${name}">${pairs.map(([id,text])=>`<option value="${e(id)}" ${id===value?'selected':''}>${e(text)}</option>`).join('')}</select></label>`;
const people=s=>[s.player,...s.squad,...s.enemies.filter(a=>a.visible!==false)];
const personName=(s,id)=>id==='player'?'{{user}}':findActor(s,id)?.name||id;
const checks=(s,ids,name)=>people(s).map(a=>check(personName(s,a.id),name+'-'+a.id,ids?.includes(a.id))).join('');
const checkedIds=(form,prefix)=>[...form.querySelectorAll('input[type=checkbox]:checked')].filter(n=>n.name.startsWith(prefix+'-')).map(n=>n.name.slice(prefix.length+1));
const status={pending:'Ожидает решения',proposal:'Нужна проверка',confirmed:'Подтверждено',rejected:'Отклонено'};
export const campaignUI={
 navigation(s){
  const n=s.navigation,j=activeJourney(s),route=j&&(s.routes.find(r=>r.id===j.routeId)||j.routeSnapshot);
  return `<div class="vh-toolbar">${btn('Сведения о транспорте','editNavigation')}${btn('Участники сцены','sceneForm')}${btn('Добавить маршрут','routeForm')}</div><dl class="vh-dossier">${this.rows({'Местонахождение':n.location,'Транспорт':n.transport,'Положение':n.relationship,'Доступ':n.access.join(', ')||'Не определён','Управление маршрутом':n.routeAuthority?'Подтверждено':'Не подтверждено'})}</dl>${n.ship?`<details class="vh-record"><summary>Сведения о корабле</summary><pre>${e(JSON.stringify(n.ship,null,2))}</pre></details>`:'<p class="vh-meta">Корабль не назначается автоматически. Переход может выполняться пассажиром, по суше или через доступный проход.</p>'}
  ${j?`<article class="vh-record"><h3>${e(j.name)}</h3><p>${e(j.origin)} → ${e(j.destination)}</p><p><strong>${JOURNEY_STAGES[j.status]}</strong> · этап ${j.progress}/${j.steps}</p><progress max="${e(j.steps)}" value="${e(j.progress)}" aria-label="Прогресс перехода"></progress><p class="vh-meta">Участники: ${e(j.travelerIds.map(id=>personName(s,id)).join(', '))}</p>${j.complication?`<p>${e(j.complication.text)}</p><p>${j.complication.resolved?'Разрешение подтверждено':'Препятствие ещё не разрешено'}</p>`:''}${['planned','awaiting_access'].includes(j.status)?`<ul>${journeyBlockers(s,route).map(t=>`<li>${e(t)}</li>`).join('')}</ul>`:''}<div class="vh-toolbar">${['planned','awaiting_access'].includes(j.status)?btn('Запросить доступ','journeyAction',`data-kind="journey-request"`)+btn('Отправиться','journeyAction',`data-kind="journey-depart"`)+btn('Отменить план','journeyAction',`data-kind="journey-cancel"`):['underway','interrupted'].includes(j.status)?btn('Продолжить переход','journeyAction',`data-kind="journey-advance"`):btn('Подтвердить прибытие','journeyAction',`data-kind="journey-arrive"`)}${btn('Условия по истории','journeyReview',`data-id="${e(j.id)}"`)}</div></article>`:'<p class="vh-empty">Активного перехода нет. Выберите маршрут и участников.</p>'}
  ${this.hub.pending?.plan.some(a=>a.kind==='journey-advance')?btn('Бросить d100 и продолжить','approveRolls'):""}<h3>Маршруты</h3>${s.routes.map(r=>`<article class="vh-record"><h3>${e(r.name)}</h3><p>${e(r.origin)} → ${e(r.destination)} · ${e(TRAVEL_MODES.find(([id])=>id===r.mode)?.[1])}</p><p>${e(r.steps)} этап(а) · риск ${e({safe:'5%',watch:'20%',dangerous:'40%',unknown:'20% · условная оценка'}[r.risk])}</p><p>${e(r.requirements.join('; ')||'Дополнительные условия не записаны')}</p><div class="vh-toolbar">${!j?btn('Спланировать поездку','journeyForm',`data-id="${e(r.id)}"`):''}${btn('Изменить','routeForm',`data-id="${e(r.id)}"`)}${!j||j.routeId!==r.id?btn('Удалить','remove',`data-collection="routes" data-id="${e(r.id)}"`):''}</div></article>`).join('')}
  <details class="vh-record"><summary>История переходов</summary>${s.journeys.filter(v=>['arrived','cancelled'].includes(v.status)).map(v=>`<p>${e(v.name)} · ${JOURNEY_STAGES[v.status]} · ${e(v.destination)}</p>`).join('')||'<p>Завершённых переходов нет.</p>'}</details>`;
 },
 careerSection(s){const p=s.player,profile=serviceFor(p);return `<details class="vh-record"><summary>Карьера и полномочия</summary><dl class="vh-dossier">${this.rows({'Служба':profile.name,'Ранг':p.rank,'Должность':p.position,'Статус':p.serviceStatus,'Полномочия':p.permissions.join(', ')||'Не определены','Обязательства':p.obligations||'Не определены'})}</dl><p class="vh-meta">${e(profile.note)}</p><div class="vh-toolbar">${btn('Запрос / изменение службы','careerForm')}${btn('Настроить профиль службы','serviceForm')}</div>${s.careerEvents.slice().reverse().map(v=>`<article class="vh-record"><h3>${e(CAREER_TYPES[v.type])} · ${e(status[v.status])}</h3><p>${e(v.reason)}</p>${v.evidence?`<blockquote>${e(v.evidence)}</blockquote>`:''}<p>${e([v.newRank,v.newPosition,v.newAffiliation].filter(Boolean).join(' · '))}</p>${['pending','proposal'].includes(v.status)?btn('Проверить по истории','careerReview',`data-id="${e(v.id)}"`):''}</article>`).join('')||'<p class="vh-empty">Служебных событий пока нет.</p>'}</details>`;},
 memorySection(s,owner='player'){const records=s.memories.filter(m=>m.ownerId===owner);return `<details class="vh-record"><summary>Личная память · ${e(personName(s,owner))}</summary><p class="vh-meta">Просмотр записей автора. В запрос NPC попадают только подтверждённые знания, доступные этому NPC.</p>${btn('Добавить известное событие','memoryForm',`data-owner="${e(owner)}"`)}${records.map(m=>`<article class="vh-record"><p>${e(m.text)}</p><p class="vh-meta">${m.confirmed?'Подтверждено':'Предложение · не используется'} · ${e(m.source)} · ${e(m.reliability)}</p>${m.evidence?`<blockquote>${e(m.evidence)}</blockquote>`:''}<p class="vh-meta">${m.public?'Открытое знание':m.sharedWith.length?'Также известно: '+e(m.sharedWith.map(id=>personName(s,id)).join(', ')):'Личная запись'}</p>${btn('Проверить / изменить','memoryForm',`data-id="${e(m.id)}"`)}${btn('Удалить','remove',`data-collection="memories" data-id="${e(m.id)}"`)}</article>`).join('')||'<p>Записей пока нет.</p>'}</details>`;},
 campaignEditor(s){const ed=this.editor,r=ed.record||{},end=this.formButtons(),profile=serviceFor(s.player);
  if(ed.type==='route')return `<form data-form="campaign-route"><h3>Маршрут</h3>${field('Название','name',r.name)}${field('Отправление','origin',r.origin||s.navigation.location)}${field('Назначение','destination',r.destination)}${select('Способ','mode',TRAVEL_MODES,r.mode||'custom')}${field('Число этапов (1–100)','steps',r.steps||3,'number')}${select('Риск препятствия за этап','risk',[['safe','Низкий · 5%'],['watch','Умеренный · 20%'],['dangerous','Высокий · 40%'],['unknown','Неизвестный · условно 20%']],r.risk||'unknown')}${area('Необходимые условия, по одному в строке','requirements',(r.requirements||[]).join('\n'))}<p class="vh-meta">Отмечайте условия, когда они установлены в истории. Вид транспорта не даёт доступ автоматически.</p>${check('Доступ / разрешение подтверждены','accessGranted',r.accessGranted)}${check('Подходящий транспорт / проход есть','transportConfirmed',r.transportConfirmed)}${check('Условия перехода выполнены','conditionsConfirmed',r.conditionsConfirmed)}${check('Нужно отдельное разрешение на посадку / вход','landingRequired',r.landingRequired)}${check('Посадка / вход разрешены','landingGranted',r.landingGranted)}${end}</form>`;
  if(ed.type==='journey')return `<form data-form="campaign-journey"><h3>Участники перехода «${e(r.name)}»</h3>${s.squad.map(a=>check(a.name,'traveler-'+a.id,false)).join('')}<p class="vh-meta">{{user}} участвует автоматически. Спутников нужно выбирать по истории.</p>${select('Действие','kind',[['journey-plan','План поездки / пассажирский маршрут'],...(s.navigation.routeAuthority?[['route-command','Задать маршрут транспорта по полномочиям']]:[])],'journey-plan')}${end}</form>`;
  if(ed.type==='journeyReview')return `<form data-form="campaign-journeyReview"><h3>Подтверждение условий по истории</h3>${area('Основание / событие','evidence',r.evidence||'')}${r.complication?check('Препятствие разрешено','resolved',r.complication.resolved):''}${check('Посадка / вход разрешены','landingGranted',r.landingGranted)}${end}</form>`;
  if(ed.type==='scene')return `<form data-form="campaign-scene"><h3>Кто присутствует в текущей сцене</h3>${field('Место сцены','location',s.navigation.location)}${checks(s,r.presentIds,'present')}${check('Присутствие подтверждено по истории','confirmed',r.confirmed)}<p class="vh-meta">Присутствие относится к текущей сцене. Смена места требует нового подтверждения. Оно не делает NPC свидетелем старых закрытых разговоров.</p>${end}</form>`;
  if(ed.type==='service')return `<form data-form="campaign-service">${select('Профиль службы (по принадлежности, не по расе)','serviceProfile',SERVICE_PROFILES.map(p=>[p.id,p.name]),profile.id)}${field('Статус службы','serviceStatus',s.player.serviceStatus)}<p class="vh-meta">Настройка правил службы не повышает ранг и не отменяет обязательства.</p>${end}</form>`;
  if(ed.type==='career'||ed.type==='careerReview')return `<form data-form="campaign-${ed.type}"><h3>${ed.type==='career'?'Запрос / намерение':'Проверка служебного события'}</h3>${select('Тип события','type',Object.entries(CAREER_TYPES),r.type||'appointment')}${area('Основание / намерение','reason',r.reason||'')}<label class="vh-field">Новый ранг · можно свой<input name="newRank" list="vh-service-ranks" value="${e(r.newRank)}"><datalist id="vh-service-ranks">${profile.ranks.map(rank=>`<option value="${e(rank)}"></option>`).join('')}</datalist></label>${field('Новая должность','newPosition',r.newPosition)}${field('Новая принадлежность','newAffiliation',r.newAffiliation)}${select('Подтверждающее лицо','authorityId',[['','Не определено'],...people(s).filter(a=>a.id!=='player').map(a=>[a.id,a.name])],r.authorityId||'')}${select('Основание выхода','exitBasis',[['','Не выбрано'],...profile.exits.map(id=>[id,EXIT_BASES[id]])],r.exitBasis||'')}${ed.type==='careerReview'?`${select('Решение автора','decision',[['rejected','Отклонить / оставить без изменения службы'],['confirmed','Подтвердить вручную по истории']],'rejected')}${area('Событие, подтверждающее решение','confirmationNote','')}${area('Новые полномочия, по одному в строке; пусто = сохранить','permissions',(r.permissions||[]).join('\n'))}${area('Новые обязательства; пусто = сохранить','obligations',r.obligations||'')}<h3>Кому известно событие</h3>${checks(s,r.knownIds||['player'],'known')}<p class="vh-meta">Ручное решение автора заменяет проверку полномочий NPC. Оно должно соответствовать событиям истории; обязательства не исчезают от самовольного ухода.</p>`:'<p class="vh-meta">Запрос уйдёт в основной чат. Ранг и полномочия изменятся после подтверждённого решения.</p>'}${end}</form>`;
  if(ed.type==='memory')return `<form data-form="campaign-memory"><h3>Личная память</h3>${select('Владелец знания','ownerId',people(s).map(a=>[a.id,personName(s,a.id)]),r.ownerId||'player')}${area('Что ему известно','text',r.text)}${field('Источник','source',r.source||'manual')}${field('Достоверность','reliability',r.reliability||'По истории')}${r.evidence?`<blockquote>${e(r.evidence)}</blockquote>`:''}${check('Знание подтверждено автором по истории','confirmed',r.confirmed)}${check('Событие известно открыто','public',r.public)}<h3>Кому это было передано</h3>${checks(s,r.sharedWith,'shared')}<p class="vh-meta">Отмеченные участники получат запись в своём контексте. Неподтверждённые записи не используются.</p>${end}</form>`;
  return null;
 },
 async campaignAction(action,d,s){
  const edits={routeForm:'route',journeyForm:'journey',journeyReview:'journeyReview',sceneForm:'scene',careerForm:'career',careerReview:'careerReview',serviceForm:'service',memoryForm:'memory'};
  if(edits[action]){const collections={routeForm:'routes',journeyForm:'routes',journeyReview:'journeys',careerReview:'careerEvents',memoryForm:'memories'};const record=d.id?clone(s[collections[action]]?.find(r=>r.id===d.id)):action==='sceneForm'?clone(s.scene):action==='memoryForm'?{id:uid(),ownerId:d.owner||'player',source:'manual',confirmed:true,sharedWith:[]}:action==='routeForm'?{id:uid(),origin:s.navigation.location}:{};if(d.id&&!record)throw Error('Запись больше не существует');this.edit({type:edits[action],record});return true;}
  if(action==='journeyAction'){const j=activeJourney(s);if(!j)throw Error('Нет активного перехода');const texts={'journey-request':`{{user}} запрашивает доступ к переходу «${j.name}».`,'journey-depart':`{{user}} отправляется по маршруту «${j.name}» с подтверждёнными участниками.`,'journey-advance':`Продолжаем переход «${j.name}». Опиши текущую обстановку и ближайший шаг с учётом положения {{user}}.`,'journey-arrive':`{{user}} завершает переход «${j.name}» и прибывает в ${j.destination}.`,'journey-cancel':`{{user}} отменяет план поездки «${j.name}».`};await this.sendTactical(texts[d.kind],{kind:d.kind,actorId:'player',journeyId:j.id});return true;}
  return false;
 },
 async campaignSubmit(form,data,lines,type,s){if(!type.startsWith('campaign-'))return false;const r=this.editor.record;
  if(type==='campaign-journey'){await this.sendTactical(`{{user}} планирует переход «${r.name}»: ${r.origin} → ${r.destination}.`,{kind:data.kind,actorId:'player',routeId:r.id,travelerIds:checkedIds(form,'traveler')});return true;}
  if(type==='campaign-career'){await this.sendTactical(`{{user}}: ${CAREER_TYPES[data.type]}. ${data.reason}. Рассмотри намерение с учётом службы, полномочий и обязательств {{user}}.`,{...data,kind:'career-request',actorId:'player'});return true;}
  let update;
  if(type==='campaign-route'){const route={...r,...data,steps:Number(data.steps),requirements:lines('requirements')};for(const flag of ['accessGranted','transportConfirmed','conditionsConfirmed','landingRequired','landingGranted'])route[flag]=form.elements[flag].checked;if(!route.name.trim()||!route.origin.trim()||!route.destination.trim())throw Error('Укажите название, отправление и назначение');update={routes:[route]};}
  if(type==='campaign-journeyReview'){if(!data.evidence.trim())throw Error('Укажите событие, подтверждающее изменение');const next={...r,evidence:data.evidence,landingGranted:form.elements.landingGranted.checked};if(next.complication)next.complication={...next.complication,resolved:form.elements.resolved.checked};update={journeys:[next]};}
  if(type==='campaign-scene'){if(data.location!==s.navigation.location&&form.elements.confirmed.checked)throw Error('Место сцены должно совпадать с текущим местонахождением');update={scene:{location:data.location,presentIds:checkedIds(form,'present'),confirmed:form.elements.confirmed.checked}};}
  if(type==='campaign-service')update={player:{serviceProfile:data.serviceProfile,serviceStatus:data.serviceStatus}};
  if(type==='campaign-memory'){if(!data.text.trim())throw Error('Добавьте известное событие');update={memories:[{...r,...data,confirmed:form.elements.confirmed.checked,public:form.elements.public.checked,sharedWith:checkedIds(form,'shared')}]};}
  if(type==='campaign-careerReview'){if(data.decision==='confirmed'&&!data.confirmationNote.trim())throw Error('Укажите событие, которым подтверждено решение');const event={...r,...data,reason:data.reason+(data.confirmationNote?'\nПодтверждение: '+data.confirmationNote:''),evidence:data.confirmationNote,knownIds:checkedIds(form,'known')};if(data.permissions.trim())event.permissions=lines('permissions');else delete event.permissions;if(!data.obligations.trim())delete event.obligations;this.hub.reviewCareer(event,data.decision==='confirmed');this.editor=null;this.render();return true;}
  this.editor=null;this.hub.update(update,'review');return true;
 }
};
