import {worldUI,WORLD_UI_ACTIONS} from './world-ui.js';
import {campaignUI} from './campaign-ui.js';
import {VERSION,STAT_NAMES,REGIONS,COLLECTIONS,uid,clone,actor,findActor,activeEvents,attackReport,hash,validateUpdate} from './core.js';
import {SPECIES,PROFILES} from './presets.js';
import {ABILITY_TEMPLATES,abilityFromTemplate,canUseAbility,availableSupply,participants,reportFor} from './tactics.js';
import {EFFECT_TEMPLATES,effectFromTemplate,physiologyOf} from './effects.js';
import {CREATURE_PROFILES,WEAPON_TEMPLATES,ARMOR_TEMPLATES,profilesFor,applyCreatureProfile,weaponFromTemplate,armorFromTemplate,damageRange} from './balance.js';
import {validateProfile} from './onboarding.js';

const TITLES={briefing:'Сводка',missions:'Миссии',vox:'Вокс',navigation:'Навигация',profile:'Досье',battle:'Бой',squad:'Отряд',arsenal:'Арсенал',archive:'Архив',settings:'Настройки'};
export const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHTML;
const button=(label,action,data='',className='')=>`<button type="button" class="vh-button ${className}" data-action="${action}" ${data}>${label}</button>`;
const empty=text=>`<p class="vh-empty">${e(text)}</p>`;
const options=(values,current,custom=true)=>[...values,...(custom?['__custom__']:[])].map(v=>`<option value="${e(v)}" ${v===current?'selected':''}>${v==='__custom__'?'Свой вариант':v===''?'Выберите вариант':e(v)}</option>`).join('');
const field=(label,name,value,type='text')=>`<label class="vh-field">${e(label)}<input name="${name}" type="${type}" value="${e(value)}" ${type==='number'?'step="1"':''}></label>`;
const area=(label,name,value,rows=3)=>`<label class="vh-field">${e(label)}<textarea name="${name}" rows="${rows}">${e(value)}</textarea></label>`;
const icon=name=>`<i class="fa-solid fa-${name}" aria-hidden="true"></i>`;

export class UI {
 constructor(hub){this.hub=hub;this.tab='briefing';this.scroll={};this.missionFilter='active';this.channelId=null;this.region='chest';this.editor=null;this.traits=[];this.opened=false;this.busy=false;}
 mount(){
  if(document.getElementById('voidhub-window'))return;
  const root=document.createElement('section');root.id='voidhub-window';root.hidden=true;root.setAttribute('role','dialog');root.setAttribute('aria-label','VOIDHUB');root.setAttribute('aria-modal','true');
  root.innerHTML=`<div class="vh-shell"><header class="vh-header"><button class="vh-brand" type="button" data-action="tab" data-tab="profile" aria-label="Открыть досье">${icon('skull')} VOIDHUB</button><div class="vh-header-tools">${button(icon('rotate'),'sync','','vh-icon')}<button type="button" class="vh-button vh-icon" data-action="close" aria-label="Закрыть VOIDHUB">${icon('xmark')}</button></div></header><div class="vh-subhead"><span id="vh-tab-title">Сводка</span><span id="vh-sync-state" role="status"></span></div><div class="vh-content" id="vh-content"></div><div id="vh-status" class="vh-status" role="status" hidden></div><div id="vh-more" class="vh-more" hidden>${['profile','battle','squad','arsenal','archive','settings'].map(t=>button(TITLES[t],'tab',`data-tab="${t}"`)).join('')}</div><nav class="vh-nav" aria-label="Разделы VOIDHUB">${[['briefing','satellite-dish'],['missions','scroll'],['vox','tower-broadcast'],['navigation','compass']].map(([t,i])=>button(`${icon(i)}<span>${TITLES[t]}</span>`,'tab',`data-tab="${t}"`)).join('')}${button(`${icon('ellipsis')}<span>Ещё</span>`,'more','aria-expanded="false"')}</nav></div>`;
  document.body.append(root);this.root=root;this.content=root.querySelector('#vh-content');
  const creationFooter=document.createElement('footer');creationFooter.className='vh-creation-footer';creationFooter.hidden=true;creationFooter.innerHTML='<button type="submit" form="vh-player-form" class="vh-button">Создать персонажа</button>';root.querySelector('.vh-shell').insertBefore(creationFooter,root.querySelector('#vh-more'));
  root.addEventListener('click',event=>{const control=event.target.closest('[data-action]');if(control&&root.contains(control))void this.action(control.dataset.action,control.dataset).catch(error=>this.hub.fail(error));});
  root.addEventListener('submit',event=>{event.preventDefault();void this.submit(event.target).catch(error=>this.hub.fail(error));});
  root.addEventListener('change',event=>this.changed(event.target));
  this.content.addEventListener('scroll',()=>{this.scroll[this.tab]=this.content.scrollTop;},{passive:true});
  root.addEventListener('keydown',event=>{if(event.key==='Escape'){if(this.editor){this.editor=null;this.render();}else this.close();}if(event.key==='Tab'){const controls=[...root.querySelectorAll('button,input,textarea,select,summary')].filter(n=>!n.disabled&&n.getClientRects().length);if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
  const open=document.createElement('button');open.type='button';open.id='voidhub-open';open.className='list-group-item flex-container flexGap5';open.setAttribute('aria-label','Открыть VOIDHUB');open.innerHTML='<span class="extensionsMenuExtensionButton voidhub-aquila-icon" aria-hidden="true"></span><span>VOIDHUB</span>';open.addEventListener('click',()=>this.open());
  const attachLauncher=()=>{const menu=document.getElementById('extensionsMenu');if(!menu)return false;if(open.parentElement!==menu)menu.append(open);return true;};
  if(!attachLauncher()){const observer=new window.MutationObserver(()=>{if(attachLauncher())observer.disconnect();});observer.observe(document.body,{childList:true,subtree:true});}
  const settings=document.getElementById('extensions_settings2')||document.getElementById('extensions_settings');if(settings){const note=document.createElement('div');note.className='voidhub-settings-entry';note.innerHTML=`<strong>VOIDHUB ${VERSION}</strong><button type="button" class="menu_button">Открыть терминал</button>`;note.querySelector('button').addEventListener('click',()=>this.open());settings.append(note);}
  const viewport=()=>{root.style.setProperty('--vh-viewport-height',`${window.visualViewport?.height||window.innerHeight}px`);root.style.top=`${window.visualViewport?.offsetTop||0}px`;if(root.contains(document.activeElement))document.activeElement.scrollIntoView?.({block:'nearest'});};
  window.visualViewport?.addEventListener('resize',viewport);window.visualViewport?.addEventListener('scroll',viewport);window.addEventListener('resize',viewport);viewport();
  root.querySelector('[data-action=sync]').setAttribute('aria-label','Синхронизировать с основным чатом');
  this.render();
 }
 open(){this.returnFocus=document.activeElement;this.hub.startProfile();this.root.hidden=false;this.opened=true;this.render();(this.root.querySelector('[name=name]')||this.root.querySelector('.vh-brand')).focus();}
 close(){this.root.hidden=true;this.opened=false;this.returnFocus?.focus?.();}
 switch(tab){if(!this.hub.profileReady()){this.render();return;}this.scroll[this.tab]=this.content.scrollTop;this.tab=tab;this.editor=null;this.root.querySelector('#vh-more').hidden=true;this.render();}
 render(){
  if(!this.root)return;
  const identity=this.hub.ready()?this.hub.identity():null;
  if(identity!==this.chatIdentity){this.chatIdentity=identity;this.editor=null;this.traits=[];this.scroll={};}
  const creating=this.hub.ready()&&!this.hub.profileReady();
  this.root.classList.toggle('vh-creating',creating);
  this.root.querySelector('.vh-creation-footer').hidden=!creating;
  this.root.querySelector('.vh-nav').hidden=creating||!this.hub.ready();
  this.root.querySelector('[data-action=sync]').hidden=creating||!this.hub.ready();
  this.root.querySelector('.vh-brand').disabled=creating;
  if(creating){
   this.root.querySelector('#vh-more').hidden=true;
   if(!this.editor?.onboarding){const record=clone(this.hub.state().player);if(record.name==='{{user}}')record.name=this.hub.context().name1||'';this.editor={type:'player',record,onboarding:true,force:true};this.traits=[...record.traits];this.scroll[this.tab]=0;}
  }else if(this.editor?.onboarding)this.editor=null;
  this.root.querySelector('#vh-tab-title').textContent=creating?'Создание персонажа':TITLES[this.tab];
  const focused=this.root.contains(document.activeElement)?document.activeElement:null;
  // Keep unsaved editor inputs intact while background state updates.
  if(this.editor&&this.content.querySelector('form')&&!this.editor.force){this.status();this.chatReports();return;}
  if(this.editor)this.editor.force=false;
  const oldScroll=this.scroll[this.tab]??0;
  this.root.style.setProperty('--vh-font-size',`${this.hub.settings.fontSize||16}px`);
  this.root.querySelectorAll('.vh-nav [data-tab]').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===this.tab?'page':'false'));
  this.root.querySelector('.vh-nav [data-action=more]').setAttribute('aria-current',['briefing','missions','vox','navigation'].includes(this.tab)?'false':'page');
  if(!this.hub.ready()){this.content.innerHTML=empty('Откройте чат SillyTavern, чтобы создать или продолжить кампанию VOIDHUB.');this.status();return;}
  const state=this.hub.state();
  this.content.innerHTML=this.editor?this.editorHTML(state):this.view(state);
  for(const select of this.content.querySelectorAll('select[data-vh-initial]'))select.value=select.dataset.vhInitial;
  this.content.scrollTop=oldScroll;this.status();this.chatReports();
  if(focused?.dataset?.action){[...this.root.querySelectorAll('[data-action]')].find(node=>Object.entries(focused.dataset).every(([key,value])=>node.dataset[key]===value))?.focus();}
 }
 status(){
  const element=this.root.querySelector('#vh-status');element.hidden=!this.hub.error;element.textContent=this.hub.error;
  this.root.querySelector('#vh-sync-state').textContent=this.root.classList.contains('vh-creating')?'Заполните анкету':this.hub.syncing?'Синхронизация…':this.busy?'Обработка…':this.hub.settings.enabled?'Связь с чатом':'Связь отключена';
 }
 chatReports(){
  const chat=this.hub.context().chat||[];
  document.querySelectorAll('.voidhub-chat-rolls').forEach(n=>n.remove());
  chat.forEach((message,index)=>{
   const data=message.extra?.voidhub;if(!data?.reports?.length||data.reportSignature!==hash(message.mes))return;
   const node=document.querySelector(`#chat .mes[mesid="${index}"] .mes_block`);if(!node)return;
   const report=document.createElement('details');report.className='voidhub-chat-rolls';const title=document.createElement('summary');title.textContent='VOIDHUB · результаты действия';const text=document.createElement('pre');text.textContent=data.reports.join('\n\n');report.append(title,text);node.append(report);
  });
 }
 view(s){
  if(this.tab==='briefing')return `<div class="vh-toolbar">${button('Добавить сообщение','create','data-collection="feed"')}</div>${s.feed.length?s.feed.map(f=>`<article class="vh-record"><div class="vh-meta">${e(f.source||'Источник не указан')} · ${e(f.time||'Время не указано')} · ${e(f.reliability||'Не проверено')}</div><h3>${e(f.title||'Сообщение')}</h3><p>${e(f.text)}</p>${this.editButtons('feed',f.id)}</article>`).join(''):empty('Новостей пока нет. Сводка заполняется доступными {{user}} сообщениями из истории.')}`;
  if(this.tab==='missions')return this.missions(s);
  if(this.tab==='profile')return this.profile(s.player);
  if(this.tab==='battle')return this.battle(s);
  if(this.tab==='vox')return this.vox(s);
  if(this.tab==='squad')return `<div class="vh-toolbar">${button('Добавить спутника','create','data-collection="squad"')}</div>${s.squad.map(a=>this.actorCard(a,'squad')).join('')||empty('Отряд пока не сформирован. Экипаж появляется, если он есть в вашей истории.')}`;
  if(this.tab==='navigation')return this.navigation(s);
  if(this.tab==='arsenal')return this.offersSection(s)+this.catalogueHTML()+['weapons','armor','inventory','abilities'].map(c=>`<section><div class="vh-toolbar"><h3>${{weapons:'Оружие',armor:'Броня',inventory:'Предметы',abilities:'Способности'}[c]}</h3>${button('Добавить','create',`data-collection="${c}"`)}</div>${s[c].map(r=>`<article class="vh-record"><h3>${e(r.name)}</h3><p>${c==='weapons'?`${e(r.damage)} · пробитие ${e(r.penetration)} · ${r.ammo===null?'без расхода патронов':e(r.ammo)+' патронов'}`:c==='abilities'?e(r.power)+' · '+e(r.charges===null?'без счётчика':r.charges+' зарядов'):c==='inventory'?e(r.amount??r.value??'')+' · '+e(r.description||''):e(r.description||'')}</p>${this.editButtons(c,r.id)}</article>`).join('')||empty('Записей пока нет.')}</section>`).join('');
  if(this.tab==='archive')return `<div class="vh-toolbar">${button('Добавить запись','create','data-collection="archive"')}</div>${s.archive.map(r=>`<article class="vh-record"><h3>${e(r.title||r.name||'Запись')}</h3><p>${e(r.text||r.description)}</p>${this.editButtons('archive',r.id)}</article>`).join('')}<h3>Журнал изменений</h3>${activeEvents(this.hub.book,this.hub.path).slice().reverse().map(event=>`<details class="vh-record"><summary>${e(event.kind==='attack'?'Бросок':event.source==='story'?'События чата':'Изменение')} · ${e(event.id)}</summary><pre>${e(['attack','mechanic'].includes(event.kind)?reportFor(event.payload):JSON.stringify(event.payload,null,2))}</pre></details>`).join('')||empty('Записей пока нет.')}`;
  if(this.tab==='settings')return this.settingsHTML();return '';
 }
 rows(values){return Object.entries(values).map(([label,value])=>`<div><dt>${e(label)}</dt><dd>${e(value)}</dd></div>`).join('');}
 editButtons(collection,id){return `<div class="vh-toolbar">${button('Изменить','edit',`data-collection="${collection}" data-id="${e(id)}"`)}${button('Удалить','remove',`data-collection="${collection}" data-id="${e(id)}"`)}</div>`;}
 actorCard(a,collection){return `<article class="vh-record"><div class="vh-toolbar"><h3>${e(a.name)}</h3><span>${e(a.hp)} / ${e(a.maxHp)}</span></div><p>${e(a.species)} · ${e(a.role||'Роль не указана')} · ${e(a.status)}</p><p class="vh-meta">${e(CREATURE_PROFILES.find(p=>p.id===a.balanceProfile)?.name||'Свой боевой профиль')}</p><p class="vh-meta">${e(a.affiliation)} · ${e(a.location)}</p>${this.editButtons(collection,a.id)}${button('Личное отношение','relationshipForm',`data-npc="${e(a.id)}"`)}${button('Помощь / ремонт','treatmentForm',`data-id="${e(a.id)}"`)}${button('Эффекты','effectsForm',`data-id="${e(a.id)}"`)}${collection==='squad'?button('Написать в воксе','contact',`data-id="${e(a.id)}"`):''}</article>`;}
 missions(s){const filter=this.missionFilter,matching=s.missions.filter(m=>filter==='completed'?['completed','failed','abandoned','declined'].includes(m.status):m.status===filter);
  return `<div class="vh-filters" aria-label="Статус миссий">${[['available','Доступные'],['active','Активные'],['completed','Завершённые']].map(([id,label])=>button(label,'missionFilter',`data-filter="${id}" aria-pressed="${id===filter}"`)).join('')}</div><div class="vh-toolbar">${button('Добавить миссию','create','data-collection="missions"')}</div>${matching.map(m=>`<details class="vh-record"><summary><span>${e(m.title)}</span><span class="vh-meta">${e(m.location||'Место не указано')}</span></summary><p>${e(m.description)}</p><dl class="vh-dossier">${this.rows({'Источник':m.source||'Не указан','Награда':m.reward||'Не определена','Срок':m.deadline||'Без срока'})}</dl><ul class="vh-goals">${m.goals.map((g,i)=>`<li><label><input type="checkbox" data-mission-goal="${e(m.id)}" data-goal-index="${i}" ${g.done?'checked':''}> ${e(g.text)}${g.required===false?' · дополнительная':''}</label></li>`).join('')}</ul><div class="vh-toolbar">${m.status==='available'?button('Принять','acceptMission',`data-id="${e(m.id)}"`)+button('Отказаться','declineMission',`data-id="${e(m.id)}"`):m.status==='active'?button('Продолжить в основном чате','continueMission',`data-id="${e(m.id)}"`)+button('Отказаться от выполнения','abandonMission',`data-id="${e(m.id)}"`):''}</div>${this.missionExtras(s,m)}${this.editButtons('missions',m.id)}</details>`).join('')||empty('В этом списке пока нет миссий.')}`;
 }
 profile(p){
  const standard=Object.keys(p.anatomy).join(',')===Object.keys(REGIONS).join(',');
  const wounds=p.wounds.filter(w=>w.region===this.region);
  return `<div class="vh-toolbar">${button('Изменить досье','editPlayer')}${button('Подобрать по истории','sync')}${button('Лечение / ремонт','treatmentForm','data-id="player"')}${button('Способность','abilityForm')}${button('Редактор эффектов','effectsForm','data-id="player"')}</div><div class="vh-health"><span>Здоровье <strong>${e(p.hp)} <small>/ ${e(p.maxHp)}</small></strong></span><span>${e(p.status)}</span></div><meter min="0" max="${e(p.maxHp)}" value="${e(p.hp)}" aria-label="Здоровье"></meter><div class="vh-body-layout">${standard?this.bodyMap(p):`<div class="vh-region-grid">${Object.entries(p.anatomy).map(([id,label])=>button(e(label),'region',`data-region="${e(id)}" aria-pressed="${this.region===id}"`,p.wounds.some(w=>w.region===id)?'vh-damaged':'')).join('')}</div>`}<div><h3>${e(p.anatomy[this.region]||'Повреждения')}</h3>${wounds.map(w=>`<p><strong>${e(w.name)}</strong> · ${e(w.severity)}<br>${w.treated?'Обработано':'Не обработано'}</p>`).join('')||empty('Повреждений этой области нет.')}<div class="vh-wound-list">${p.wounds.map(w=>button(`${e(p.anatomy[w.region]||w.region)} · ${e(w.name)}`,'region',`data-region="${e(w.region)}"`)).join('')}</div></div></div><dl class="vh-dossier">${this.rows({'Раса / тип':p.species,'Принадлежность':p.affiliation||'Не указана','Роль':p.role||'Не указана','Происхождение':p.origin,'Среда / прошлое':p.background,'Особенности':p.traits.join(', ')||'Не указаны'})}</dl><details class="vh-record"><summary>Характеристики</summary><dl class="vh-dossier">${this.rows(Object.fromEntries(Object.entries(STAT_NAMES).map(([key,name])=>[name,p.stats[key]])))}</dl></details>${this.protectionView(p)}${this.careerSection(this.hub.state())}${this.memorySection(this.hub.state(),'player')}${this.relationshipsSection(this.hub.state())}${this.threatsSection(this.hub.state())}<details class="vh-record"><summary>Эффекты · ${p.effects.length}</summary>${this.effectsHTML(p)||empty('Активных эффектов нет.')}</details>${['resources','reputation'].map(c=>`<details class="vh-record"><summary>${c==='resources'?'Ресурсы':'Репутация'}</summary>${button('Добавить','create',`data-collection="${c}"`)}${this.hub.state()[c].map(r=>`<p>${e(r.name)}: ${e(r.value??r.amount??r.description)}</p>${this.editButtons(c,r.id)}`).join('')}</details>`).join('')}`;
 }
 bodyMap(p){return `<div class="vh-body" role="group" aria-label="Схема тела спереди. Левая сторона персонажа показана справа."><div class="vh-body-neck"></div><div class="vh-body-hips"></div>${Object.entries(REGIONS).map(([id,label])=>{const w=p.wounds.filter(w=>w.region===id);return `<button type="button" class="vh-body-part vh-part-${id} ${w.length?'vh-damaged':''}" data-action="region" data-region="${id}" aria-label="${e(label)}: ${e(w.map(r=>r.name).join(', ')||'повреждений нет')}" aria-pressed="${this.region===id}"><span>${w.length?e(w.length):''}</span></button>`;}).join('')}<span class="vh-body-caption">Вид спереди</span></div>`;}
 battle(s){const enemies=s.enemies.filter(a=>a.visible!==false);return `<div class="vh-toolbar">${button('Добавить противника','create','data-collection="enemies"')}${button(s.battle.active?'Завершить бой':'Начать бой','toggleBattle')}</div>${this.hub.pending?`<article class="vh-record"><h3>Проверки подготовлены</h3>${button('Бросить','approveRolls')}</article>`:''}<p class="vh-meta">HP и экипировка: собственный баланс VOIDHUB. Раса и снаряжение выбираются отдельно.</p>${this.tacticalBar(s)}<p>${s.battle.active?'Бой идёт':'Бой не активен'} · ${e(s.battle.notes)}</p><h3>{{user}} и отряд</h3>${[s.player,...s.squad].map(a=>`<div class="vh-combatant"><span>${e(a.name)} · ${e(a.status)}</span><strong>${e(a.hp)} / ${e(a.maxHp)}</strong></div>`).join('')}<h3>Противники</h3>${enemies.map(a=>`<article class="vh-record"><div class="vh-toolbar"><h3>${e(a.name)}</h3><strong>${e(a.hp)} / ${e(a.maxHp)}</strong></div><meter min="0" max="${e(a.maxHp)}" value="${e(a.hp)}" aria-label="Здоровье ${e(a.name)}"></meter><p>${e(a.status)} · ${e(a.wounds.map(w=>`${a.anatomy[w.region]||w.region}: ${w.name}`).join('; ')||'Повреждений нет')}</p>${a.hp>0?button('Атаковать','attackForm',`data-id="${e(a.id)}"`):''}${this.editButtons('enemies',a.id)}</article>`).join('')||empty('Обнаруженных противников пока нет.')}<h3>Последние броски</h3>${activeEvents(this.hub.book,this.hub.path).filter(event=>['attack','mechanic'].includes(event.kind)).slice(-8).reverse().map(event=>`<details class="vh-record"><summary>${e(event.kind==='attack'?event.payload.actorName+' → '+event.payload.targetName+' · '+event.payload.damage+' урона':this.mechanicTitle(event.payload.kind))}</summary><pre>${e(reportFor(event.payload))}</pre></details>`).join('')||empty('Бросков пока нет. Полная история хранится в архиве.')}`;}
 vox(s){
  const channels=s.channels.filter(c=>c.public||c.participants.includes('player')||c.participants.includes('{{user}}'));
  const channel=channels.find(c=>c.id===this.channelId)||channels[0];if(channel)this.channelId=channel.id;
  const speakers=channel?.participants.filter(id=>id!=='player'&&findActor(s,id))||[],speaker=speakers.includes(this.speakerId)?this.speakerId:speakers[0];this.speakerId=speaker;
  return `<div class="vh-toolbar">${button('Создать канал','create','data-collection="channels"')}</div>${channels.length?`<label class="vh-field">Канал<select id="vh-channel-picker">${options(channels.map(c=>c.id),channel.id,false).replace(/>([^<]*)<\/option>/g,(m,id)=>'>'+e(channels.find(c=>c.id===id)?.name||id)+'</option>')}</select></label><p class="vh-meta">Участники: ${e(channel.participants.join(', '))} · ${channel.public?'Открытый канал':'Закрытый канал'}</p>${this.editButtons('channels',channel.id)}<div class="vh-messages">${channel.messages.map(m=>`<article class="vh-message"><strong>${e(m.from)}</strong><p>${e(m.text)}</p></article>`).join('')||empty('Сообщений пока нет.')}</div><form data-form="vox">${speakers.length?`<label class="vh-field">Кто отвечает<select name="speakerId" id="vh-speaker-picker">${speakers.map(id=>`<option value="${e(id)}" ${id===speaker?'selected':''}>${e(findActor(s,id)?.name)}</option>`).join('')}</select></label>`:''}<label class="vh-field">Сообщение<textarea name="message" rows="3" required></textarea></label><button type="submit" class="vh-button">Отправить</button></form>${this.memorySection(s,speaker||'player')}${speaker?this.relationshipsSection(s,speaker):''}`:empty('Каналов пока нет. Можно создать личный разговор, канал отряда или официальный канал.')}`;
 }
 settingsHTML(){const s=this.hub.settings;return `<form data-form="settings"><label class="vh-check"><input type="checkbox" name="enabled" ${s.enabled?'checked':''}>Передавать контекст VOIDHUB</label><label class="vh-check"><input type="checkbox" name="autoSync" ${s.autoSync?'checked':''}>Обновлять состояние по ответам ИИ</label><label class="vh-check"><input type="checkbox" name="autoRoll" ${s.autoRoll?'checked':''}>Выполнять броски автоматически</label>${field('Размер основного текста','fontSize',s.fontSize,'number')}${field('Резерв контекста для инструкций и ответа','reserve',s.reserve,'number')}<p class="vh-meta">Передаётся полное состояние и весь журнал активной ветки. При переполнении запрос останавливается. Автоматический разбор использует дополнительные запросы к выбранной модели SillyTavern.</p><button type="submit" class="vh-button">Сохранить настройки</button></form><div class="vh-toolbar">${button('Экспорт кампании','export')}${button('Импорт кампании','import')}</div><input id="vh-import-file" type="file" accept="application/json,.json" hidden><p class="vh-meta">VOIDHUB ${VERSION} · прототип расширения</p>`;}
 profilePicker(label,key,values,current){const preset=values.includes(current)?current:'__custom__';return `<label class="vh-field">${label}<select name="${key}" data-profile-picker="${key}">${options(values,preset)}</select></label><label class="vh-field vh-own" data-own="${key}" ${preset==='__custom__'?'':'hidden'}>Свой вариант<input name="${key}Own" value="${preset==='__custom__'?e(current):''}" ${preset==='__custom__'?'':'disabled'}></label>`;}
 playerEditorHTML(s,p,creating){
  const config=PROFILES[p.species]||PROFILES.__custom__,origin=p.origin==='Не указано'?'':p.origin,background=p.background==='Не указано'?'':p.background;
  const identity=`<label class="vh-field">Имя персонажа<input type="text" name="name" value="${e(p.name)}" required maxlength="120" autocomplete="off"></label>${this.profilePicker('Раса / тип существа','species',SPECIES,p.species)}${this.profilePicker('Принадлежность','affiliation',['',...config.affiliations],p.affiliation)}${this.profilePicker('Роль','role',['',...config.roles],p.role)}${this.profilePicker('Происхождение · место','origin',['',...config.origins],origin)}${this.profilePicker('Происхождение · среда / прошлое','background',['',...config.backgrounds],background)}<label class="vh-field">Особенности · можно выбрать несколько<select id="vh-trait-picker"><option value="">Выберите особенность</option>${Object.entries(config.traits).map(([group,values])=>`<optgroup label="${e(group)}">${options(values,'',false)}</optgroup>`).join('')}<option value="__custom__">Свой вариант</option></select></label><label class="vh-field" id="vh-trait-own-wrap" hidden>Своя особенность<input id="vh-trait-own" disabled></label>${button('Добавить особенность','addTrait')}<div id="vh-chosen-traits">${this.traitHTML()}</div><label class="vh-check"><input type="checkbox" name="noTraits" ${!creating&&!p.traits.length?'checked':''}>Без особых особенностей</label>`;
  const numbers=`${this.creatureControls(p)}<div class="vh-fields">${field('Здоровье','hp',p.hp,'number')}${field('Максимум здоровья','maxHp',p.maxHp,'number')}</div>${field('Состояние','status',p.status)}<h3>Характеристики</h3><div class="vh-fields">${Object.entries(STAT_NAMES).map(([key,label])=>field(label,key,p.stats[key],'number')).join('')}</div>`;
  const body=creating?'':`${this.actorTacticalEditor(p,s)}<details class="vh-record"><summary>Повреждения и защита</summary><h3>Ранения</h3>${p.wounds.map(w=>`<p>${e(p.anatomy[w.region]||'Область тела')}: ${e(w.name)} · ${e(w.severity)} · ${w.treated?'обработано':'не обработано'}</p>`).join('')||empty('Ранений нет.')}<h3>Эффекты</h3>${this.effectsHTML(p)||empty('Эффектов нет.')}<p class="vh-meta">Лечение и изменение эффектов доступны в досье.</p><h3>Названия областей тела</h3>${Object.entries(p.anatomy).map(([id,label])=>field('Область тела','anatomy-label-'+id,label)).join('')}${this.protectionEditor(p)}<h3>Доступное оружие</h3>${s.weapons.map(w=>`<label class="vh-check"><input type="checkbox" name="weapon-${e(w.id)}" value="${e(w.id)}" ${p.weaponIds.includes(w.id)?'checked':''}>${e(w.name)}</label>`).join('')||empty('Оружие добавляется в арсенале.')}</details><details class="vh-record"><summary>Карьера и полномочия</summary>${field('Звание / ранг','rank',p.rank)}${field('Должность','position',p.position)}${area('Полномочия, по одному в строке','permissions',p.permissions.join('\n'))}${area('Обязательства','obligations',p.obligations)}</details>`;
  return `<form id="vh-player-form" data-form="player"><h3>${creating?'Создайте своего персонажа':'Анкета персонажа'}</h3>${creating?'<p class="vh-meta">Заполните анкету. После сохранения откроются миссии, вокс и остальные разделы VOIDHUB.</p>':''}${identity}<details><summary>Начальная ситуация · необязательно</summary>${area('Начало новой истории','start',p.start)}</details><details class="vh-record"><summary>${creating?'Стартовые характеристики · необязательно':'Боевой профиль и характеристики'}</summary>${numbers}</details>${body}${creating?`<div class="vh-toolbar">${button('Импортировать кампанию','import')}</div><input id="vh-import-file" type="file" accept="application/json,.json" hidden>`:this.formButtons()}</form>`;
 }
 editorHTML(s){const ed=this.editor,r=ed.record||{};
  const world=this.worldEditor(s);if(world!==null)return world;
  const campaign=this.campaignEditor(s);if(campaign!==null)return campaign;
  if(ed.type==='player')return this.playerEditorHTML(s,r,ed.onboarding===true);
  if(ed.type==='attack'){
   const weapons=s.weapons.filter(w=>s.player.weaponIds.includes(w.id));
   return `<form data-form="attack"><h3>Атака: ${e(r.name)}</h3>${weapons.length?`<label class="vh-field">Оружие<select name="weaponId">${weapons.map(w=>`<option value="${e(w.id)}">${e(w.name)} · ${e(w.damage)}</option>`).join('')}</select></label><label class="vh-field">Область<select name="region"><option value="">Обычная атака</option>${Object.entries(r.anatomy).map(([id,label])=>`<option value="${e(id)}">${e(label)} · штраф −20</option>`).join('')}</select></label><label class="vh-check"><input name="aim" type="checkbox">Прицеливание +10</label><label class="vh-check"><input name="cover" type="checkbox">Цель в укрытии −20</label><label class="vh-check"><input name="wound" type="checkbox">Мешающее ранение −10</label>${this.formButtons('Атаковать')}`:empty('Назначьте {{user}} оружие в арсенале или досье.')+button('Назад','cancelEdit')}</form>`;
  }
  if(ed.type==='treatment')return this.treatmentHTML(s,ed.record);
  if(ed.type==='ability')return this.abilityHTML(s);
  if(ed.type==='effects')return this.effectEditorHTML(ed.record);
  if(ed.type==='navigation')return `<form data-form="navigation">${['location','transport','relationship','route'].map(k=>field({location:'Местонахождение',transport:'Транспорт',relationship:'Связь с транспортом',route:'Маршрут'}[k],k,r[k])).join('')}${area('Доступ, по одному в строке','access',r.access.join('\n'))}<label class="vh-check"><input type="checkbox" name="routeAuthority" ${r.routeAuthority?'checked':''}>Право управлять маршрутом подтверждено по истории</label>${area('Корабль — JSON или null','ship',JSON.stringify(r.ship,null,2),5)}${this.formButtons()}</form>`;
  const c=ed.collection;
  if(c==='abilities')return this.abilityEditorHTML(s,r);
  if(c==='inventory')return `<form data-form="inventory">${field('Название','name',r.name)}<label class="vh-field">Назначение<select name="tag">${[['item','Предмет'],['medkit','Медицинский комплект'],['repairkit','Ремонтный комплект']].map(([id,name])=>`<option value="${id}" ${r.tag===id?'selected':''}>${name}</option>`).join('')}</select></label>${field('Количество применений / предметов','amount',r.amount??r.value??1,'number')}<label class="vh-field">Владелец<select name="ownerId"><option value="party" ${r.ownerId==='party'?'selected':''}>Общий запас отряда</option>${participants(s).map(a=>`<option value="${e(a.id)}" ${(r.ownerId||'player')===a.id?'selected':''}>${e(a.name)}</option>`).join('')}</select></label>${area('Описание','description',r.description)}${this.formButtons()}</form>`;
  if(c==='missions')return `<form data-form="record">${field('Название','title',r.title)}${field('Источник / заказчик','source',r.source)}${field('Место','location',r.location)}${area('Описание','description',r.description)}${area('Цели, по одной в строке; ? в начале = дополнительная','goals',(r.goals||[]).map(g=>(g.required===false?'? ':'')+(g.text||g)).join('\n'))}${field('Награда','reward',r.reward)}${field('Срок по игровому времени','deadline',r.deadline)}<label class="vh-field">Статус<select name="status">${options(['available','active','completed','failed','abandoned','declined'],r.status||'available',false)}</select></label>${this.formButtons()}</form>`;
  if(c==='weapons')return `<form data-form="record">${this.templateControls('weapons',r)}${field('Название оружия','name',r.name)}<label class="vh-field">Режим<select name="mode">${options(['ranged','melee'],r.mode||'ranged',false)}</select></label>${field('Урон, например 2d10+20','damage',r.damage||'2d10+20')}${field('Пробитие','penetration',r.penetration??8,'number')}${field('Боеприпасы, пустое поле = без счётчика','ammo',r.ammo??'','number')}${field('Расход за атаку','cost',r.cost??1,'number')}${field('Тип воздействия','type',r.type||'кинетический')}${area('Дальность и свойства','description',r.description)}<label class="vh-check"><input type="checkbox" name="assign" ${s.player.weaponIds.includes(r.id)?'checked':''}>Назначить {{user}}</label>${this.formButtons()}</form>`;
  if(c==='feed')return `<form data-form="record">${field('Заголовок','title',r.title)}${field('Источник','source',r.source)}${field('Время истории','time',r.time)}${field('Достоверность','reliability',r.reliability)}<label class="vh-check"><input type="checkbox" name="public" ${r.public===true?'checked':''}>Сообщение известно открыто</label>${area('Сообщение','text',r.text)}${this.formButtons()}</form>`;
  if(c==='channels')return `<form data-form="record">${field('Название канала','name',r.name)}${area('ID участников, по одному в строке (player = {{user}})','participants',(r.participants||['player']).join('\n'))}<label class="vh-check"><input type="checkbox" name="public" ${r.public?'checked':''}>Открытый канал</label>${this.formButtons()}</form>`;
  if(c==='squad'||c==='enemies')return `<form data-form="participant">${field('Имя','name',r.name)}${this.profilePicker('Раса / тип существа','species',SPECIES,r.species)}${this.creatureControls(r)}${field('Принадлежность','affiliation',r.affiliation)}${field('Роль','role',r.role)}${field('Местонахождение','location',r.location)}<div class="vh-fields">${field('Здоровье','hp',r.hp,'number')}${field('Максимум здоровья','maxHp',r.maxHp,'number')}</div>${field('Состояние','status',r.status)}${this.actorTacticalEditor(r,s)}<h3>Характеристики</h3><div class="vh-fields">${Object.entries(STAT_NAMES).map(([key,label])=>field(label,key,r.stats[key],'number')).join('')}</div><h3>Доступное оружие</h3>${s.weapons.map(w=>`<label class="vh-check"><input name="weapon-${e(w.id)}" type="checkbox" value="${e(w.id)}" ${r.weaponIds.includes(w.id)?'checked':''}>${e(w.name)}</label>`).join('')||empty('Добавьте оружие в арсенале.')}${this.protectionEditor(r)}<details><summary>Дополнительные сведения</summary>${field('Звание / ранг','rank',r.rank)}${field('Должность','position',r.position)}${area('Полномочия (appoint / release — в своей организации; appoint_any / release_any — общий допуск)','permissions',(r.permissions||[]).join('\n'))}${area('Обязательства','obligations',r.obligations)}${area('Повреждения — JSON','wounds',JSON.stringify(r.wounds,null,2),4)}${area('Эффекты — JSON','effects',JSON.stringify(r.effects,null,2),4)}${area('Анатомия — JSON','anatomy',JSON.stringify(r.anatomy,null,2),5)}</details>${this.formButtons()}</form>`;
  if(c==='armor')return `<form data-form="armor">${this.templateControls('armor',r)}${field('Название','name',r.name)}${field('Защита','protection',r.protection??10,'number')}<h3>Защищаемые области</h3>${Object.entries(s.player.anatomy).map(([id,label])=>`<label class="vh-check"><input type="checkbox" name="region-${e(id)}" value="${e(id)}" ${(r.regions||[]).includes(id)?'checked':''}>${e(label)}</label>`).join('')}${area('Свойства','description',r.description)}<label class="vh-check"><input name="equip" type="checkbox">Надеть на {{user}}</label>${this.formButtons()}</form>`;
  if(c==='archive')return `<form data-form="record">${field('Название','title',r.title||r.name)}${area('Запись','text',r.text||r.description,8)}${this.formButtons()}</form>`;
  return `<form data-form="record">${field('Название','name',r.name)}${field(c==='resources'?'Количество / значение':c==='reputation'?'Отношение':'Количество','value',r.value??r.amount??'')}${area('Описание','description',r.description)}${this.formButtons()}</form>`;
 }
 creatureOptions(species,current){return '<option value="">Свой профиль / ручная настройка</option>'+profilesFor(species).map(p=>`<option value="${e(p.id)}" ${p.id===current?'selected':''}>${e(p.name)} · ${p.maxHp} HP</option>`).join('');}
 creatureControls(a){return `<details class="vh-record" open><summary>Боевой профиль</summary><label class="vh-field">Основа характеристик<select name="balanceProfile">${this.creatureOptions(a.species,a.balanceProfile)}</select></label>${button('Применить профиль','applyCreature')}<p data-balance-note class="vh-meta">${e(CREATURE_PROFILES.find(p=>p.id===a.balanceProfile)?.note||'Выберите подходящую основу или задайте значения вручную.')}</p><p class="vh-meta">Собственные числа VOIDHUB. Профиль задаёт максимум HP, характеристики и природную защиту. Сохраняются потерянные HP, ранения и эффекты; HP 0 остаётся 0. Оружие и надетая броня выбираются отдельно. Изменения вступят в силу после сохранения.</p></details>`;}
 balanceNote(form){const note=form.querySelector('[data-balance-note]'),p=CREATURE_PROFILES.find(p=>p.id===form.elements.balanceProfile.value);if(note)note.textContent=p?.note||'Стартовая основа; все значения можно изменить вручную.';}
 protectionEditor(a){return `<h3>Защита по областям</h3><p class="vh-meta">Надетая броня и природная защита (хитин, живой металл) суммируются. Пробитие уменьшает их общую защиту. Несколько комплектов надетой брони не складываются.</p>${Object.entries(a.anatomy).map(([id,label])=>`<div class="vh-fields">${field(label+' · броня','protection-'+id,a.armor[id]||0,'number')}${field(label+' · природная','natural-'+id,a.naturalArmor?.[id]||0,'number')}</div>`).join('')}`;}
 protectionView(a){return `<details class="vh-record"><summary>Броня и природная защита</summary><dl class="vh-dossier">${this.rows(Object.fromEntries(Object.entries(a.anatomy).map(([id,label])=>[label,`броня ${a.armor[id]||0} + природная ${a.naturalArmor?.[id]||0}`])))}</dl></details>`;}
 templateControls(collection,r){const templates=collection==='weapons'?WEAPON_TEMPLATES:ARMOR_TEMPLATES;return `<details class="vh-record" open><summary>Образцы ${collection==='weapons'?'оружия':'брони'} 40к</summary><label class="vh-field">Выберите образец<select name="templateChoice"><option value="">Свой вариант</option>${templates.map(t=>`<option value="${e(t.id)}" ${t.id===r.templateId?'selected':''}>${e(t.name)} · ${collection==='weapons'?e(t.damage)+' / пробитие '+t.penetration:'защита '+t.protection}</option>`).join('')}</select></label>${button('Применить образец','applyTemplate',`data-collection="${collection}"`)}<p class="vh-meta">Заполняет поля формы; можно изменить перед сохранением. Для существующего оружия текущий боезапас сохраняется. Выбирайте размер, носитель и доступность по истории.</p></details>`;}
 applyCreatureDraft(){
  const form=this.content.querySelector('form'),data=Object.fromEntries(new FormData(form)),species=data.species==='__custom__'?data.speciesOwn.trim():data.species;
  const anatomy=data.anatomy?JSON.parse(data.anatomy):Object.fromEntries(Object.entries(this.editor.record.anatomy).map(([id,label])=>[id,data['anatomy-label-'+id]??label]));
  const draft={...this.editor.record,species,hp:Number(data.hp),maxHp:Number(data.maxHp),anatomy},next=applyCreatureProfile(draft,data.balanceProfile);
  for(const k of ['hp','maxHp'])form.elements[k].value=next[k];for(const [k,v] of Object.entries(next.stats))form.elements[k].value=v;
  for(const [k,v] of Object.entries(next.naturalArmor))if(form.elements['natural-'+k])form.elements['natural-'+k].value=v;
  this.editor.record.balanceProfile=next.balanceProfile;this.editor.record.naturalArmor=clone(next.naturalArmor);this.balanceNote(form);
 }
 applyTemplateDraft(collection){
  const form=this.content.querySelector('form'),id=form.elements.templateChoice.value,original=this.editor.record;
  const template=collection==='weapons'?weaponFromTemplate(id,original.id):armorFromTemplate(id,this.hub.state().player.anatomy,original.id);
  for(const [key,value] of Object.entries(template))if(form.elements[key]&&!['id','ammo'].includes(key))form.elements[key].value=value;
  if(collection==='weapons'&&this.editor.newRecord)form.elements.ammo.value=template.ammo??'';
  if(collection==='armor')for(const input of form.querySelectorAll('input[name^="region-"]'))input.checked=template.regions.includes(input.value);
  this.editor.record.templateId=id;
 }
 catalogueHTML(){return `<details class="vh-record"><summary>Справочник баланса 40к</summary><p class="vh-meta">Собственный стартовый баланс VOIDHUB. Все значения редактируются. Справочник не выдаёт предметы персонажу.</p><details><summary>Существа · ${CREATURE_PROFILES.length}</summary>${CREATURE_PROFILES.map(p=>`<p><strong>${e(p.name)}</strong> · ${p.maxHp} HP · природная защита ${p.naturalProtection}${p.note?'<br>'+e(p.note):''}</p>`).join('')}</details><details><summary>Оружие · ${WEAPON_TEMPLATES.length}</summary>${WEAPON_TEMPLATES.map(w=>{const r=damageRange(w);return `<p><strong>${e(w.name)}</strong> · ${e(w.damage)} · ${r.min}–${r.max} урона · пробитие ${w.penetration}${w.mode==='melee'?' + сила / 10':''}${w.description?'<br>'+e(w.description):''}</p>`;}).join('')}</details><details><summary>Броня · ${ARMOR_TEMPLATES.length}</summary>${ARMOR_TEMPLATES.map(a=>`<p><strong>${e(a.name)}</strong> · защита ${a.protection}${a.description?'<br>'+e(a.description):''}</p>`).join('')}</details></details>`;}
 mechanicTitle(kind){return {initiative:'Инициатива',treatment:'Помощь / ремонт',ability:'Способность',round:'Завершение раунда',wait:'Пропуск действия',end:'Завершение боя'}[kind]||'Действие';}
 effectsHTML(a){return a.effects.map(effect=>`<p>${e(typeof effect==='string'?effect:effect.name)}${typeof effect==='object'?` · ${effect.remaining===null||effect.remaining===undefined?'до снятия':effect.remaining+' раунд(а)'}${effect.shieldPoints!==undefined?' · поле '+effect.shieldPoints:''}<br>${e(effect.description||'')}`:''}</p>`).join('');}
 tacticalBar(s){return `<details class="vh-record" open><summary>Раунд ${e(s.battle.round||1)} · инициатива</summary>${(s.battle.order||[]).map((o,i)=>`<p>${i+1}. ${e(o.name)} · ${e(o.score)}</p>`).join('')||empty('Порядок определяется при начале боя.')}<p class="vh-meta">Одно выбранное боевое действие запускает раунд. Участники действуют по инициативе, затем один раз срабатывают эффекты. Обычная реплика не продвигает время.</p><div class="vh-toolbar">${button('Лечение / ремонт','treatmentForm','data-id="player"')}${button('Способность','abilityForm')}${s.battle.active?button('Пропустить действие','waitTurn'):''}${button(s.battle.active?'Раунд без действий':'Продвинуть эффекты на один такт','advanceRound')}</div></details><details class="vh-record"><summary>Эффекты участников</summary>${participants(s).filter(a=>a.effects.length).map(a=>`<h3>${e(a.name)}</h3>${this.effectsHTML(a)}${button('Изменить эффекты','effectsForm',`data-id="${e(a.id)}"`)}`).join('')||empty('Активных эффектов нет.')}</details>`;}
 actorTacticalEditor(a,s){return `<details class="vh-record"><summary>Тело и доступные способности</summary><label class="vh-field">Тип тела<select name="physiology">${[['auto','По расе'],['biological','Органическое'],['mechanical','Механическое'],['warp','Варп-форма'],['mixed','Смешанное / кибернетическое']].map(([id,label])=>`<option value="${id}" ${(a.physiology||'auto')===id?'selected':''}>${label}</option>`).join('')}</select></label><label class="vh-check"><input type="checkbox" name="psychic" ${a.psychic?'checked':''}>Пользование Варпом подтверждено историей</label><label class="vh-check"><input type="checkbox" name="psychicOverride" ${a.psychicOverride?'checked':''}>Особое исключение из обычного лора подтверждено историей</label><label class="vh-check"><input type="checkbox" name="destroyed" ${a.destroyed?'checked':''}>Окончательно погиб / тело полностью уничтожено</label><p class="vh-meta">HP 0 означает выведение из боя. Последний флажок задаётся только по событию истории.</p>${s.abilities.map(power=>`<label class="vh-check"><input name="ability-${e(power.id)}" type="checkbox" value="${e(power.id)}" ${a.abilityIds.includes(power.id)?'checked':''}>${e(power.name)}</label>`).join('')||empty('Способности добавляются отдельно в арсенале. Они не выдаются по расе.')}</details>`;}
 tacticalFormData(form){return {physiology:form.elements.physiology.value,psychic:form.elements.psychic.checked,psychicOverride:form.elements.psychicOverride.checked,destroyed:form.elements.destroyed.checked,abilityIds:[...form.querySelectorAll('input[name^="ability-"]:checked')].map(i=>i.value)};}
 actorOptions(s,current){return participants(s).map(a=>`<option value="${e(a.id)}" ${a.id===current?'selected':''}>${e(a.name)} · ${a.hp}/${a.maxHp}</option>`).join('');}
 treatmentHTML(s,target){const source=[s.player,...s.squad].find(a=>a.hp>0&&!a.destroyed)||s.player,kind=physiologyOf(target)==='mechanical'?'repair':target.hp===0?'stabilize':'heal',supplies=availableSupply(s,source.id,kind==='repair'?'repairkit':'medkit');return `<form data-form="treatment"><h3>Помощь и ремонт</h3><label class="vh-field">Кто выполняет<select name="actorId">${this.actorOptions({...s,enemies:[]},source.id)}</select></label><label class="vh-field">Цель<select name="targetId">${this.actorOptions(s,target.id)}</select></label><label class="vh-field">Действие<select name="kind">${[['heal','Первая помощь'],['stabilize','Стабилизация при HP 0'],['repair','Ремонт']].map(([id,label])=>`<option value="${id}" ${id===kind?'selected':''}>${label}</option>`).join('')}</select></label><label class="vh-field">Расходный комплект<select name="supplyId">${this.supplyOptions(supplies)}</select></label><p class="vh-meta">Воля +10; расходуется одно применение на попытку. Первая помощь / ремонт: 2d10+10 HP. Стабилизация оставляет HP 0. Сохранившиеся раны требуют дальнейшего лечения. Комплекты добавляются в арсенале.</p>${this.formButtons('Продолжить в основном чате')}</form>`;}
 supplyOptions(supplies){return supplies.length?supplies.map(i=>`<option value="${e(i.id)}">${e(i.name)} · ${e(i.amount)} применений</option>`).join(''):'<option value="">Доступных комплектов нет</option>';}
 refreshSupplies(form){form.elements.supplyId.innerHTML=this.supplyOptions(availableSupply(this.hub.state(),form.elements.actorId.value,form.elements.kind.value==='repair'?'repairkit':'medkit'));}
 abilityOptions(s,source){const powers=s.abilities.filter(a=>source.abilityIds.includes(a.id));return powers.length?powers.map(a=>{const reason=canUseAbility(source,a)||(s.battle.active&&(source.cooldowns[a.id]||0)>s.battle.round?'Восстанавливается':'');return `<option value="${e(a.id)}" ${reason?'disabled':''}>${e(a.name)} · ${reason|| (a.charges===null?'без счётчика':a.charges+' зарядов')}</option>`;}).join(''):'<option value="">Назначенных способностей нет</option>';}
 abilityHTML(s){return `<form data-form="ability"><h3>Особая способность</h3><label class="vh-field">Владелец<select name="actorId">${this.actorOptions({...s,enemies:[]},'player')}</select></label><label class="vh-field">Способность<select name="abilityId">${this.abilityOptions(s,s.player)}</select></label><label class="vh-field">Цель<select name="targetId">${this.actorOptions(s,'player')}</select></label><p class="vh-meta">Способности назначаются в арсенале или досье. Для пси-сил нужен подтверждённый доступ к Варпу. Правила цели и восстановления проверяются при выполнении.</p>${this.formButtons('Применить в основном чате')}</form>`;}
 refreshAbilities(form){form.elements.abilityId.innerHTML=this.abilityOptions(this.hub.state(),findActor(this.hub.state(),form.elements.actorId.value));}
 abilityEditorHTML(s,r){return `<form data-form="abilityRecord"><details class="vh-record" open><summary>Образцы способностей</summary><label class="vh-field">Выберите основу<select name="templateChoice"><option value="">Свой вариант</option>${ABILITY_TEMPLATES.map(a=>`<option value="${e(a.id)}" ${a.id===r.templateId?'selected':''}>${e(a.name)}</option>`).join('')}</select></label>${button('Применить образец','applyAbilityTemplate')}</details>${field('Название','name',r.name)}<label class="vh-field">Действие<select name="kind">${[['damage','Урон'],['heal','Восстановление'],['effect','Эффект'],['cleanse','Снять потрясение / подавление'],['reanimate','Реанимация некрона']].map(([id,label])=>`<option value="${id}" ${(r.kind||'damage')===id?'selected':''}>${label}</option>`).join('')}</select></label><label class="vh-field">Проверка<select name="skill">${Object.entries(STAT_NAMES).map(([id,label])=>`<option value="${id}" ${(r.skill||'will')===id?'selected':''}>${label}</option>`).join('')}</select></label>${field('Урон / восстановление кубиками','power',r.power||'2d10+20')}${field('Пробитие для урона','penetration',r.penetration||0,'number')}<label class="vh-field">Эффект<select name="effectId">${EFFECT_TEMPLATES.map(t=>`<option value="${t.id}" ${r.effectId===t.id?'selected':''}>${e(t.name)}</option>`).join('')}</select></label><label class="vh-field">Сопротивление цели<select name="resist">${options(['','will','toughness'],r.resist||'',false)}</select></label><label class="vh-field">Тело для восстановления<select name="targetPhysiology">${options(['any','biological','mechanical','warp','mixed'],r.targetPhysiology||'any',false)}</select></label>${field('Заряды, пустое поле = без счётчика','charges',r.charges??'','number')}${field('Восстановление, раундов','cooldown',r.cooldown??1,'number')}${area('Допустимые расы, по одной в строке; пусто = любые','allowedSpecies',(r.allowedSpecies||[]).join('\n'))}<label class="vh-check"><input name="psychic" type="checkbox" ${r.psychic?'checked':''}>Пси-сила с риском Варпа</label><label class="vh-check"><input name="selfOnly" type="checkbox" ${r.selfOnly?'checked':''}>Только на владельца</label>${area('Описание и условия','description',r.description)}<label class="vh-check"><input name="assign" type="checkbox" ${s.player.abilityIds.includes(r.id)?'checked':''}>Назначить {{user}}</label>${this.formButtons()}</form>`;}
 applyAbilityDraft(){const form=this.content.querySelector('form'),id=form.elements.templateChoice.value,template=abilityFromTemplate(id,this.editor.record.id);for(const [key,value] of Object.entries(template)){const input=form.elements[key];if(!input||key==='charges'&&!this.editor.newRecord)continue;if(input.type==='checkbox')input.checked=!!value;else input.value=Array.isArray(value)?value.join('\n'):value??'';}for(const key of ['psychic','selfOnly'])form.elements[key].checked=!!template[key];form.elements.effectId.value=template.effectId||EFFECT_TEMPLATES[0].id;form.elements.resist.value=template.resist||'';this.editor.record.templateId=id;}
 effectEditorHTML(a){return `<form data-form="effects"><h3>Эффекты: ${e(a.name)}</h3><p class="vh-meta">Ручная правка состояния. Сроки отсчитываются при завершении раундов или явном продвижении времени.</p><div id="vh-effect-list">${this.effectDraftList()}</div><label class="vh-field">Добавить эффект<select name="effectChoice">${EFFECT_TEMPLATES.map(t=>`<option value="${t.id}">${e(t.name)}</option>`).join('')}<option value="__custom__">Свой эффект · описание</option></select></label>${field('Оставшиеся раунды, пусто = до снятия','remaining','', 'number')}${area('Свой эффект / примечание','effectNote','')}${button('Добавить в список','addEffectDraft')}${this.formButtons()}</form>`;}
 effectDraftList(){return this.editor.record.effects.map((effect,i)=>`<article class="vh-record">${e(typeof effect==='string'?effect:effect.name)}${typeof effect==='object'?' · '+e(effect.remaining??'до снятия'):''}${button('Удалить','removeEffectDraft',`data-index="${i}"`)}</article>`).join('')||empty('Эффектов нет.');}
 addEffectDraft(){const form=this.content.querySelector('form'),choice=form.elements.effectChoice.value,note=form.elements.effectNote.value.trim();if(choice==='__custom__'){if(note)this.editor.record.effects.push(note);}else{const t=effectFromTemplate(choice,uid(),{remaining:form.elements.remaining.value===''?null:Number(form.elements.remaining.value)});if(t.biological&&!['biological','mixed'].includes(physiologyOf(this.editor.record)))throw Error('Биологический эффект не подходит телу');if(note)t.description=note;const existing=this.editor.record.effects.findIndex(e=>e.templateId===choice);if(existing>=0)this.editor.record.effects[existing]=t;else this.editor.record.effects.push(t);}this.content.querySelector('#vh-effect-list').innerHTML=this.effectDraftList();}
 async sendTactical(text,action){if(!this.hub.settings.enabled)throw Error('Включите связь VOIDHUB с чатом для выполнения действия');this.editor=null;this.close();await this.work(()=>this.hub.send(text,{action}));}
 traitHTML(){return this.traits.map((t,i)=>`<span class="vh-trait">${e(t)} ${button('Удалить','removeTrait',`data-index="${i}"`)}</span>`).join('');}
 formButtons(label='Сохранить'){return `<div class="vh-toolbar"><button type="submit" class="vh-button">${label}</button>${button('Отмена','cancelEdit')}</div>`;}
 edit(editor){this.editor={...editor,force:true};this.scroll[this.tab]=0;if(editor.type==='player')this.traits=[...editor.record.traits];this.render();this.content.querySelector('input,select,textarea')?.focus();}
 async action(action,d){
  if(action==='close')return this.close();if(action==='tab')return this.switch(d.tab);
  if(!this.hub.profileReady()&&!['addTrait','removeTrait','applyCreature','import'].includes(action)){this.render();return;}
  if(action==='more'){const menu=this.root.querySelector('#vh-more');menu.hidden=!menu.hidden;this.root.querySelector('[data-action=more]').setAttribute('aria-expanded',String(!menu.hidden));return;}
  if(action==='cancelEdit'){this.editor=null;this.render();return;}
  if(action==='sync'){await this.work(()=>this.hub.sync(true));return;}
  const s=this.hub.state();
  if(WORLD_UI_ACTIONS.includes(action)){await this.worldAction(action,d,s);return;}
  if(['routeForm','journeyForm','journeyReview','sceneForm','careerForm','careerReview','serviceForm','memoryForm','journeyAction'].includes(action)){await this.campaignAction(action,d,s);return;}
  if(action==='editPlayer')return this.edit({type:'player',record:clone(s.player)});
  if(action==='region'){this.region=d.region;this.render();return;}
  if(action==='missionFilter'){this.missionFilter=d.filter;this.render();return;}
  if(action==='editNavigation')return this.edit({type:'navigation',record:clone(s.navigation)});
  if(action==='toggleBattle')return this.sendTactical(s.battle.active?'{{user}} завершает бой. Опиши текущие последствия.':'{{user}} начинает бой. Опиши обстановку с учётом порядка инициативы.',{kind:s.battle.active?'end':'start',actorId:'player'});
  if(action==='advanceRound')return this.sendTactical(s.battle.active?'{{user}} пропускает действия текущего раунда. Рассчитай завершение раунда.':'В сцене проходит один такт времени для текущих эффектов. Продолжи с учётом положения {{user}}.',{kind:'round',actorId:'player'});
  if(action==='waitTurn')return this.sendTactical('{{user}} пропускает своё действие в текущем боевом раунде.',{kind:'wait',actorId:'player'});
  if(action==='treatmentForm')return this.edit({type:'treatment',record:clone(findActor(s,d.id||'player'))});
  if(action==='abilityForm')return this.edit({type:'ability'});
  if(action==='effectsForm')return this.edit({type:'effects',record:clone(findActor(s,d.id||'player'))});
  if(action==='addEffectDraft')return this.addEffectDraft();
  if(action==='removeEffectDraft'){this.editor.record.effects.splice(Number(d.index),1);this.content.querySelector('#vh-effect-list').innerHTML=this.effectDraftList();return;}
  if(action==='applyAbilityTemplate')return this.applyAbilityDraft();
  if(action==='attackForm')return this.edit({type:'attack',record:clone(s.enemies.find(a=>a.id===d.id))});
  if(action==='approveRolls'){await this.work(()=>this.hub.approveRolls());return;}
  if(action==='applyCreature')return this.applyCreatureDraft();
  if(action==='applyTemplate')return this.applyTemplateDraft(d.collection);
  if(action==='create'){
   const c=d.collection,record=c==='squad'||c==='enemies'?actor({id:uid(),name:'',visible:true}):c==='missions'?{id:uid(),title:'',goals:[],status:'available'}:c==='channels'?{id:uid(),name:'',participants:['player'],public:false,messages:[]}:c==='abilities'?{id:uid(),name:'',kind:'damage',skill:'will',power:'2d10+20',penetration:0,charges:3,cooldown:1,allowedSpecies:[],targetPhysiology:'any'}:c==='weapons'?{id:uid(),name:'',mode:'ranged',damage:'2d10+20',penetration:8,ammo:20,cost:1,type:'кинетический'}:{id:uid(),name:'',description:''};
   return this.edit({type:'record',collection:c,record,newRecord:true});
  }
  if(action==='edit')return this.edit({type:'record',collection:d.collection,record:clone(s[d.collection].find(r=>r.id===d.id))});
  if(action==='remove'){this.hub.remove(d.collection,d.id);return;}
  if(action==='addTrait'){
   const picker=this.content.querySelector('#vh-trait-picker'),own=this.content.querySelector('#vh-trait-own'),value=picker.value==='__custom__'?own.value.trim():picker.value;
   if(value&&!this.traits.includes(value)){this.traits.push(value);this.content.querySelector('#vh-chosen-traits').innerHTML=this.traitHTML();if(this.content.querySelector('[name=noTraits]'))this.content.querySelector('[name=noTraits]').checked=false;}return;
  }
  if(action==='removeTrait'){this.traits.splice(Number(d.index),1);this.content.querySelector('#vh-chosen-traits').innerHTML=this.traitHTML();return;}
  if(['acceptMission','declineMission','continueMission','abandonMission'].includes(action)){
   const mission=s.missions.find(m=>m.id===d.id);if(!mission)throw Error('Миссия не найдена');
   if(action==='acceptMission')return this.sendTactical(`{{user}} принимает миссию «${mission.title}». Продолжи с учётом положения {{user}}.`,{kind:'mission-accept',actorId:'player',missionId:mission.id});
   const statuses={acceptMission:'active',declineMission:'declined',abandonMission:'abandoned'};
   const text=action==='continueMission'?`Продолжаем миссию «${mission.title}». Опиши текущую обстановку и ближайший шаг с учётом положения {{user}}.`:action==='acceptMission'?`{{user}} принимает миссию «${mission.title}». Продолжи с учётом текущего положения {{user}}.`:action==='declineMission'?`{{user}} отказывается принять миссию «${mission.title}».`:`{{user}} заявляет об отказе от выполнения миссии «${mission.title}». Учти обязательства {{user}} и реакцию заказчика по истории.`;
   this.close();await this.work(()=>this.hub.send(text,{operation:statuses[action]?{missions:[{...mission,status:statuses[action]}]}:null}));return;
  }
  if(action==='contact'){
   const npc=s.squad.find(a=>a.id===d.id),channel=s.channels.find(c=>c.participants.includes(d.id)&&c.participants.includes('player'));
   if(channel)this.channelId=channel.id;else{const newChannel={id:uid(),name:npc.name,participants:['player',npc.id],public:false,messages:[]};this.hub.update({channels:[newChannel]});this.channelId=newChannel.id;}this.switch('vox');return;
  }
  if(action==='export'){this.download(this.hub.export(),`VOIDHUB-campaign-${Date.now()}.json`);return;}
  if(action==='import'){this.content.querySelector('#vh-import-file').click();return;}
 }
 changed(control){
  if(control.closest('form')?.dataset.form==='world-offer'&&control.name==='collection'){this.edit({type:'world-offer',record:this.offerDraft(control.form)});return;}
  if(control.closest('form')?.dataset.form==='treatment'&&['actorId','targetId','kind'].includes(control.name)){if(control.name==='targetId'){const target=findActor(this.hub.state(),control.value);control.form.elements.kind.value=physiologyOf(target)==='mechanical'?'repair':target.hp===0?'stabilize':'heal';}this.refreshSupplies(control.closest('form'));}
  if(control.closest('form')?.dataset.form==='ability'&&control.name==='actorId')this.refreshAbilities(control.closest('form'));
  if(control.name==='effectChoice'){const t=EFFECT_TEMPLATES.find(e=>e.id===control.value);control.form.elements.remaining.value=t?.remaining??'';}
  if(control.id==='vh-import-file'&&control.files[0])void control.files[0].text().then(text=>this.hub.import(text)).catch(error=>this.hub.fail(error));
  if(control.id==='vh-speaker-picker'){this.speakerId=control.value;this.render();}
  if(control.id==='vh-channel-picker'){this.channelId=control.value;this.render();}
  if(control.dataset.missionGoal){const mission=this.hub.state().missions.find(m=>m.id===control.dataset.missionGoal);mission.goals[Number(control.dataset.goalIndex)].done=control.checked;this.hub.update({missions:[mission]});}
  const key=control.dataset.profilePicker;
  if(key){
   const own=this.content.querySelector(`[data-own="${key}"]`);own.hidden=control.value!=='__custom__';own.querySelector('input').disabled=own.hidden;
   if(key==='species'){const form=control.closest('form'),picker=form?.querySelector('[name=balanceProfile]');if(picker){picker.innerHTML=this.creatureOptions(control.value,'');this.balanceNote(form);}}
   if(key==='species'&&this.editor?.type==='player'){
    const config=PROFILES[control.value]||PROFILES.__custom__;
    for(const [k,values] of Object.entries({affiliation:['',...config.affiliations],role:['',...config.roles],origin:['',...config.origins],background:['',...config.backgrounds]})){
     const select=this.content.querySelector(`[name="${k}"]`),old=select.value;select.innerHTML=options(values,values.includes(old)||old==='__custom__'?old:values[0]);
     const wrapper=this.content.querySelector(`[data-own="${k}"]`);wrapper.hidden=select.value!=='__custom__';wrapper.querySelector('input').disabled=wrapper.hidden;
    }
    const picker=this.content.querySelector('#vh-trait-picker');picker.innerHTML='<option value="">Выберите особенность</option>'+Object.entries(config.traits).map(([group,values])=>`<optgroup label="${e(group)}">${options(values,'',false)}</optgroup>`).join('')+'<option value="__custom__">Свой вариант</option>';
    this.hub.notify('Варианты обновлены. Проверьте принадлежность, роль, происхождение и уже выбранные особенности.','info');
   }
  }
  if(control.name==='balanceProfile')this.balanceNote(control.closest('form'));
  if(control.id==='vh-trait-picker'){const wrap=this.content.querySelector('#vh-trait-own-wrap'),own=this.content.querySelector('#vh-trait-own');wrap.hidden=control.value!=='__custom__';own.disabled=wrap.hidden;if(!wrap.hidden)own.focus();}
 }
 async submit(form){
  const data=Object.fromEntries(new FormData(form)),lines=name=>String(data[name]||'').split('\n').map(s=>s.trim()).filter(Boolean),type=form.dataset.form,s=this.hub.state();
  if(!this.hub.profileReady()&&type!=='player')throw Error('Сначала создайте персонажа.');
  if(await this.worldSubmit(form,data,lines,type,s))return;
  if(await this.campaignSubmit(form,data,lines,type,s))return;
  if(type==='treatment'){const action={kind:data.kind,actorId:data.actorId,targetId:data.targetId,supplyId:data.supplyId};const source=findActor(s,action.actorId),target=findActor(s,action.targetId);return this.sendTactical(`{{user}} выбирает действие «${{heal:'первая помощь',repair:'ремонт',stabilize:'стабилизация'}[action.kind]}»: ${source.name} помогает ${target.name}, используя доступный комплект.`,action);}
  if(type==='ability'){const ability=s.abilities.find(a=>a.id===data.abilityId),source=findActor(s,data.actorId),target=findActor(s,data.targetId);if(!ability)throw Error('Назначьте доступную способность участнику в арсенале или досье');return this.sendTactical(`{{user}} выбирает применение способности «${ability.name}»: ${source.name} → ${target.name}.`,{kind:'ability',actorId:source.id,targetId:target.id,abilityId:ability.id});}
  if(type==='effects'){const current=findActor(s,this.editor.record.id),next={...current,effects:clone(this.editor.record.effects)},update=next.id==='player'?{player:{effects:next.effects}}:{[s.squad.some(a=>a.id===next.id)?'squad':'enemies']:[next]};validateUpdate(update);this.editor=null;this.hub.update(update);return;}
  if(type==='settings'){Object.assign(this.hub.settings,{enabled:form.elements.enabled.checked,autoSync:form.elements.autoSync.checked,autoRoll:form.elements.autoRoll.checked,fontSize:Math.max(14,Math.min(24,Number(data.fontSize)||16)),reserve:Math.max(256,Number(data.reserve)||1500)});this.hub.context().saveSettingsDebounced();this.hub.inject();this.render();return;}
  if(type==='vox'){const value=data.message?.trim();if(!value)return;await this.work(()=>this.hub.vox(this.channelId,value,data.speakerId||null));form.reset();return;}
  if(type==='attack'){
   if(!this.hub.settings.enabled)throw Error('Включите связь VOIDHUB с чатом в настройках, чтобы использовать расчёт атаки.');
   const target=this.editor.record,weapon=s.weapons.find(w=>w.id===data.weaponId);if(!weapon)throw Error('Оружие не найдено');
   const modifiers=[...(form.elements.aim.checked?[{reason:'Прицеливание',value:10}]:[]),...(form.elements.cover.checked?[{reason:'Укрытие',value:-20}]:[]),...(form.elements.wound.checked?[{reason:'Мешающее ранение',value:-10}]:[])];
   const action={actorId:'player',targetId:target.id,weaponId:weapon.id,region:data.region||null,modifiers};
   this.editor=null;this.close();await this.work(()=>this.hub.send(`{{user}} атакует ${target.name}, используя ${weapon.name}${data.region?`, целясь в область «${target.anatomy[data.region]}»`:''}.`,{action}));return;
  }
  if(type==='player'){
   const own=k=>data[k]==='__custom__'?String(data[k+'Own']||'').trim():data[k];
   const original=this.editor.record,creating=this.editor.onboarding===true,anatomy=Object.fromEntries(Object.entries(original.anatomy).map(([id,label])=>[id,String(data['anatomy-label-'+id]??label).trim()||label]));
   const player={...original,...(form.elements.physiology?this.tacticalFormData(form):{}),...Object.fromEntries(['species','affiliation','role','origin','background'].map(k=>[k,own(k)])),name:String(data.name||'').trim(),traits:form.elements.noTraits.checked?[]:[...this.traits],start:data.start,status:data.status,hp:Number(data.hp),maxHp:Number(data.maxHp),rank:data.rank??original.rank,position:data.position??original.position,permissions:form.elements.permissions?lines('permissions'):original.permissions,obligations:data.obligations??original.obligations,stats:Object.fromEntries(Object.keys(STAT_NAMES).map(k=>[k,Number(data[k])])),anatomy,armor:creating?original.armor:Object.fromEntries(Object.keys(anatomy).map(k=>[k,Number(data['protection-'+k])||0])),naturalArmor:creating?original.naturalArmor:Object.fromEntries(Object.keys(anatomy).map(k=>[k,Number(data['natural-'+k])||0])),weaponIds:creating?original.weaponIds:[...form.querySelectorAll('input[name^="weapon-"]:checked')].map(n=>n.value)};
   if(CREATURE_PROFILES.find(p=>p.id===player.balanceProfile)?.species!==player.species)delete player.balanceProfile;
   validateProfile(player,{noTraits:form.elements.noTraits.checked});validateUpdate({player});
   if(creating){this.hub.completeProfile(player,{noTraits:form.elements.noTraits.checked});this.editor=null;this.tab='briefing';this.scroll={};this.render();}
   else{this.editor=null;this.hub.update({player});}return;
  }
  if(type==='navigation'){const navigation={...this.editor.record,...data,routeAuthority:form.elements.routeAuthority.checked,access:lines('access'),ship:JSON.parse(data.ship)};validateUpdate({navigation});this.editor=null;this.hub.update({navigation});return;}
  let record;
  const c=this.editor.collection,original=this.editor.record;
  if(type==='participant')record={...original,...data,...this.tacticalFormData(form),permissions:lines('permissions'),species:data.species==='__custom__'?data.speciesOwn.trim():data.species,hp:Number(data.hp),maxHp:Number(data.maxHp),stats:Object.fromEntries(Object.keys(STAT_NAMES).map(k=>[k,Number(data[k])])),weaponIds:[...form.querySelectorAll('input[name^="weapon-"]:checked')].map(n=>n.value),armor:Object.fromEntries(Object.keys(JSON.parse(data.anatomy)).map(k=>[k,Number(data['protection-'+k])||0])),naturalArmor:Object.fromEntries(Object.keys(JSON.parse(data.anatomy)).map(k=>[k,Number(data['natural-'+k])||0])),wounds:JSON.parse(data.wounds),effects:JSON.parse(data.effects),anatomy:JSON.parse(data.anatomy)};
  else if(type==='abilityRecord')record={...original,...data,psychic:form.elements.psychic.checked,selfOnly:form.elements.selfOnly.checked,charges:data.charges===''?null:Number(data.charges),penetration:Number(data.penetration),cooldown:Number(data.cooldown),allowedSpecies:lines('allowedSpecies')};
  else if(type==='inventory')record={...original,...data,amount:Number(data.amount)};
  else if(type==='armor')record={...original,...data,protection:Number(data.protection),regions:[...form.querySelectorAll('input[name^="region-"]:checked')].map(n=>n.value)};
  else if(type==='json')record=JSON.parse(data.json);
  else if(c==='missions')record={...original,...data,goals:lines('goals').map(line=>{const required=!line.startsWith('?'),text=line.replace(/^\?\s*/, '');return {text,required,done:original.goals?.find(g=>g.text===text)?.done||false};})};
  else if(c==='weapons')record={...original,...data,penetration:Number(data.penetration),ammo:data.ammo===''?null:Number(data.ammo),cost:Number(data.cost)};
  else if(c==='feed')record={...original,...data,public:form.elements.public.checked};
  else if(c==='channels')record={...original,...data,participants:lines('participants'),public:form.elements.public.checked};
  else record={...original,...data};
  if(c==='squad'||c==='enemies'){if(CREATURE_PROFILES.find(p=>p.id===original.balanceProfile)?.species!==record.species)delete record.balanceProfile;else record.balanceProfile=original.balanceProfile;}
  delete record.templateChoice;
  const update={[c]:[record]};
  if(c==='abilities')update.player={abilityIds:form.elements.assign.checked?[...new Set([...s.player.abilityIds,record.id])]:s.player.abilityIds.filter(id=>id!==record.id)};
  if(c==='weapons'&&form.elements.assign.checked&&record.returned)throw Error('Это оружие уже возвращено');
  if(c==='weapons')update.player={weaponIds:form.elements.assign.checked?[...new Set([...s.player.weaponIds,record.id])]:s.player.weaponIds.filter(id=>id!==record.id)};
  if(c==='armor'&&form.elements.equip.checked&&record.returned)throw Error('Эта броня уже возвращена');
  if(c==='armor'&&form.elements.equip.checked)update.player={armorSources:{...s.player.armorSources,...Object.fromEntries(record.regions.map(r=>[r,record.id]))},armor:{...s.player.armor,...Object.fromEntries(record.regions.map(r=>[r,record.protection]))}};
  validateUpdate(update);this.editor=null;this.hub.update(update);
 }
 async work(task){if(this.busy)throw Error('Дождитесь завершения текущего действия');this.busy=true;this.status();try{await task();}finally{this.busy=false;this.render();}}
 download(text,name){const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
}

Object.assign(UI.prototype,campaignUI);

Object.assign(UI.prototype,worldUI);
