import {storyDefaults} from './balance.js';
import {clone,findActor,validateRecord,hash} from './core.js';
import {ACQUISITION_METHODS,relationFor,blockingThreats,withoutProposal} from './world-data.js';
export const WORLD_ACTIONS=['equipment-acquire','equipment-return','mission-accept','mission-approach','mission-resolve'];
export const isWorldAction=a=>WORLD_ACTIONS.includes(a.kind);
const result=(id,kind,patch,report)=>({id,kind,patch,report});
export function missionBlockers(s,m){const out=[];for(const req of m.missionRequirements?.length?m.missionRequirements:(m.prerequisiteIds||[]).map(missionId=>({missionId,status:'completed',outcome:''}))){const p=s.missions.find(x=>x.id===req.missionId);if(!p||p.status!==req.status||req.outcome&&p.outcome!==req.outcome)out.push('Не выполнено предварительное условие: '+(p?.title||req.missionId)+(req.outcome?' · '+req.outcome:''));}for(const id of m.resolvedThreatIds||[]){const t=s.threats.find(t=>t.id===id);if(!t||!t.confirmed||t.status!=='resolved')out.push('Не разрешено условие кампании: '+(t?.name||id));}if(m.conditions?.length&&!m.conditionsConfirmed)out.push('Условия доступа к заданию ещё не подтверждены');if(m.providerId&&m.minTrust!==undefined&&(relationFor(s,m.providerId)?.trust??0)<Number(m.minTrust))out.push('Источник пока не предоставляет задание');return out;}
export function offerBlockers(s,o){const out=[];if(o.providerId&&(!findActor(s,o.providerId)||findActor(s,o.providerId).destroyed))out.push('Источник предложения недоступен');if(!o.confirmed)out.push('Предложение не подтверждено');if(!o.accessGranted)out.push('Получение снаряжения не разрешено / трофей не доступен');if(o.stock!==null&&!(o.stock>0))out.push('Запас исчерпан');if(o.requiredPermission&&!s.player.permissions.includes(o.requiredPermission))out.push('Нет необходимого допуска: '+o.requiredPermission);if(o.requiredAffiliation&&o.requiredAffiliation!==s.player.affiliation)out.push('Не выполнено требование принадлежности');if(o.allowedSpecies?.length&&!o.allowedSpecies.includes(s.player.species))out.push('Предмет не подходит выбранному типу существа');if(o.providerId&&(relationFor(s,o.providerId)?.trust??0)<Number(o.minTrust||0))out.push('Собеседник пока не предоставляет это предложение');if(o.location&&o.location!==s.navigation.location)out.push('Предложение находится в другом месте');if(blockingThreats(s,'blocksAcquisition').length)out.push('Действующее ограничение кампании мешает получению снаряжения');return out;}
export function acquireEquipment(s,a,id){
 const o=s.offers.find(o=>o.id===a.offerId);if(!o)throw Error('Предложение не найдено');const blockers=offerBlockers(s,o);if(blockers.length)throw Error(blockers.join('. '));
 const count=Number(a.quantity??1);if(!Number.isInteger(count)||count<1||count>20)throw Error('Количество: целое число от 1 до 20');if(o.stock!==null&&o.stock<count)throw Error('Не хватает запаса');
 const patch={offers:[{...clone(o),stock:o.stock===null?null:o.stock-count}],resources:[],inventory:[],weapons:[],armor:[],transactions:[],memories:[]};
 const total=o.method==='purchase'?Number(o.price)*count:0;
 if(!Number.isFinite(total)||total<0)throw Error('Неверная цена');
 if(total){const resource=s.resources.find(r=>r.id===o.resourceId),balance=Number(resource?.value??resource?.amount);if(!resource||!Number.isFinite(balance)||balance<total)throw Error('Недостаточно выбранного ресурса / денег');if(resource.ownerId&&!['player','party'].includes(resource.ownerId))throw Error('Ресурс принадлежит другому участнику');patch.resources.push({...clone(resource),value:balance-total,amount:balance-total});}
 if(o.method==='barter'){const item=s.inventory.find(i=>i.id===o.exchangeItemId),needed=Number(o.exchangeAmount)*count;if(!item||!['player','party'].includes(item.ownerId)||item.loan||item.returned||!Number.isFinite(needed)||needed<=0||item.amount<needed)throw Error('Нет собственных предметов для указанного обмена');patch.inventory.push({...clone(item),amount:item.amount-needed});}
 const legalOwner=['loan','issue'].includes(o.method)?o.legalOwner||o.providerId||'Организация':'player';
 const itemIds=[];for(let i=0;i<count;i++){const item=validateRecord(o.collection,storyDefaults(o.collection,{...clone(o.item),id:id+':item:'+i,ownerId:'player',custodyId:'player',legalOwner,loan:o.method==='loan',returnMissionId:o.returnMissionId||'',returnCondition:o.returnCondition||'',returned:false,acquiredFrom:o.id}));if(o.collection==='inventory'&&(!Number.isFinite(item.amount)||!(item.amount>0)))throw Error('В получаемом предмете должно быть положительное количество');patch[o.collection].push(item);itemIds.push(item.id);}
 const report=`${ACQUISITION_METHODS[o.method]}: {{user}} получает «${o.name}», ${count} шт.${total?' Расход: '+total+' '+(s.resources.find(r=>r.id===o.resourceId)?.name||'ресурса')+'.':''}${o.method==='loan'?' Это временная выдача, владелец сохраняется; условия возврата: '+(o.returnCondition||'по истории')+'.':''} Предметы не назначаются оружием и не надеваются автоматически.`;
 patch.transactions.push({id:id+':receipt',offerId:o.id,name:o.name,method:o.method,collection:o.collection,itemIds,count,total,providerId:o.providerId||'',legalOwner,returnMissionId:o.returnMissionId||'',returnCondition:o.returnCondition||'',status:'received',report});
 for(const ownerId of [...new Set(['player',o.providerId].filter(x=>findActor(s,x)))])patch.memories.push({id:id+':memory:'+ownerId,ownerId,text:report,source:'equipment',sourceId:id,confirmed:true,public:false,sharedWith:[],reliability:'Участник передачи'});
 return result(id,'equipment',patch,report);
}
export function returnEquipment(s,a,id){const t=s.transactions.find(t=>t.id===a.transactionId);if(!t||t.method!=='loan'||t.status==='returned')throw Error('Нет действующей временной выдачи');const patch={[t.collection]:[],transactions:[{...clone(t),status:'returned'}],player:{weaponIds:s.player.weaponIds.filter(x=>!t.itemIds.includes(x))}};for(const itemId of t.itemIds){const item=s[t.collection].find(i=>i.id===itemId);if(!item||item.returned||item.custodyId!=='player')throw Error('Предмет уже не находится у {{user}}');patch[t.collection].push({...clone(item),ownerId:t.legalOwner,custodyId:t.legalOwner,returned:true,...(t.collection==='inventory'?{amount:0}:{})});}const armor=clone(s.player.armor),sources=clone(s.player.armorSources||{});for(const [region,itemId] of Object.entries(sources))if(t.itemIds.includes(itemId)){armor[region]=0;delete sources[region];}patch.player.armor=armor;patch.player.armorSources=sources;const report=`{{user}} возвращает временно выданное снаряжение «${t.name}». Израсходованное количество не восстанавливается, деньги и запас предложения не начисляются.`;patch.memories=[...new Set(['player',t.providerId].filter(x=>findActor(s,x)))].map(ownerId=>({id:id+':memory:'+ownerId,ownerId,text:report,source:'equipment',sourceId:id,confirmed:true,public:false,sharedWith:[],reliability:'Участник передачи'}));return result(id,'equipment',patch,report);}
export function resolveMissionAction(s,a,id,{reviewed=false}={}){const m=s.missions.find(m=>m.id===a.missionId);if(!m)throw Error('Миссия не найдена');
 if(a.kind==='mission-accept'){if(m.status!=='available')throw Error('Принять можно доступное задание');const blockers=missionBlockers(s,m);if(blockers.length)throw Error(blockers.join('. '));return result(id,'mission',{missions:[{...clone(m),status:'active'}]},`{{user}} принимает задание «${m.title}».`);}
 if(m.status!=='active')throw Error('Для этого действия нужна активная миссия');
 if(a.kind==='mission-approach'){const approach=m.approaches?.find(x=>x.id===a.approachId);if(!approach)throw Error('Способ выполнения не найден');return result(id,'mission',{missions:[{...clone(m),selectedApproachId:approach.id}]},`{{user}} выбирает подход «${approach.name}» для «${m.title}». Это намерение, а не выполненная цель. ${approach.conditions||''}`);}
 const resolution=m.proposedResolution;
 if(!reviewed&&!(resolution?.confirmed&&resolution.status===a.status&&resolution.outcome===a.outcome))throw Error('Итог нужно подтвердить по событиям истории');
 const status=a.status;if(!['completed','failed'].includes(status))throw Error('Выберите завершение или провал');const evidence=String(a.evidence||resolution?.evidence||'').trim();if(!evidence)throw Error('Нужно основание результата');
 if(status==='completed'&&m.goals.some(g=>g.required!==false&&!g.done))throw Error('Не все обязательные цели выполнены');
 const next={...clone(m),status,outcome:String(a.outcome||''),resolutionEvidence:evidence,proposedResolution:null},patch={missions:[next]};
 return result(id,'mission',patch,`Миссия «${m.title}»: ${status==='completed'?'завершена':'провалена'}. Итог: ${next.outcome||'по подтверждённым событиям'}. ${evidence} Награда требует отдельной передачи / выдачи, не начисляется дважды.`);
}
export function resolveWorldAction(s,a,id,options={}){if(a.kind==='equipment-acquire')return acquireEquipment(s,a,id);if(a.kind==='equipment-return')return returnEquipment(s,a,id);return resolveMissionAction(s,a,id,options);}
function proof(chat,r){const i=Number(r.sourceIndex),e=String(r.evidence||'').trim();return Number.isInteger(i)&&i===chat.findLastIndex(m=>!m.is_user)&&e&&String(chat[i]?.mes||'').includes(e)?{sourceIndex:i,evidence:e}:null;}
export function applyWorldStory(s,u,chat){
 for(const c of ['relationships','offers','threats'])if(u[c])u[c]=u[c].map(r=>{const old=s[c].find(x=>x.id===r.id||c==='relationships'&&x.npcId===r.npcId),p=proof(chat,r);if(old)r.id=old.id;if(c==='relationships'&&!findActor(s,r.npcId)&&!u.squad?.some(a=>a.id===r.npcId)&&!u.enemies?.some(a=>a.id===r.npcId))return {...r,confirmed:false};if(!p)return old?{...clone(old),pending:clone(withoutProposal(r))}:{...r,confirmed:false};return {...r,...p,confirmed:true,...(c==='threats'?{knownIds:[...new Set((r.knownIds||['player']).filter(id=>id==='player'||old?.knownIds?.includes(id)))],affectedIds:(r.affectedIds||['player']).filter(id=>findActor(s,id))}:{})};});
 // Only calculated acquisition creates receipts; narration cannot repeat the financial transfer.
 if(u.transactions)delete u.transactions;
 for(const m of u.missions||[]){const old=s.missions.find(x=>x.id===m.id);if(!old)continue;if(m.conditionsConfirmed!==old.conditionsConfirmed&&!proof(chat,m))m.conditionsConfirmed=old.conditionsConfirmed;if(old.status==='active'&&['available','declined'].includes(m.status))m.status=old.status;if(['completed','failed'].includes(m.status)&&m.status!==old.status){const p=proof(chat,m);m.proposedResolution={status:m.status,outcome:String(m.outcome||''),confirmed:Boolean(p),evidence:p?.evidence||'',sourceIndex:p?.sourceIndex??-1};m.status=old.status;delete m.outcome;}if(old.status==='available'&&m.status==='active'){if(missionBlockers(s,old).length)m.status=old.status;}}
 return u;
}
export function worldGuide(){return JSON.stringify({actions:WORLD_ACTIONS,relationships:'relationships:{id,npcId,trust:-100..100,suspicion:0..100,rivalry:0..100,playerDebts:[строки],npcDebts:[строки],promises:[строки],patronage,sourceIndex,evidence}. Не меняй чувства за каждую реплику. Изменение требует события; это известное отношение, не чтение чужих мыслей.',offers:'offers:{id,name,providerId,method:purchase|issue|barter|trophy|gift|loan,collection:weapons|armor|inventory,item:параметры предмета,stock:число|null,price,resourceId,exchangeItemId,exchangeAmount,legalOwner,returnCondition,returnMissionId,requiredPermission,requiredAffiliation,minTrust,allowedSpecies:[],location,requirements:[],accessGranted:false,sourceIndex,evidence}. Нет универсальной валюты. Новый предмет / ресурс или операция не возникает от просьбы пользователя. equipment-acquire:{offerId,quantity,actorId:player}, equipment-return:{transactionId,actorId:player}. Числа передачи, запас, деньги и предметы рассчитывает код; не повторяй передачу.',missions:'Миссии: prerequisiteIds:[id завершённых заданий],missionRequirements:[{missionId,status:completed|failed,outcome}],providerId,minTrust,conditions:[условие],conditionsConfirmed:false,resolvedThreatIds:[id],approaches:[{id,name,conditions}],selectedApproachId,outcome. goal.required=false — необязательная цель. mission-accept:{missionId,actorId:player}; mission-approach:{missionId,approachId,actorId:player}; mission-resolve:{missionId,status:completed|failed,outcome,actorId:player}. Смена подхода не завершает цели. Для фактического итога передай sourceIndex,evidence; код предложит подтверждение. Не выдавай награды вторично.',threats:'threats:{id,name,type:wanted|cover|artifact|contract|warp|custom,status:active|contained|resolved,severity:1..3,source,consequences,resolutionConditions,location,affectedIds:[player],knownIds:[player],public:false,blocksTravel:false,blocksAcquisition:false,sourceIndex,evidence}. Нет универсального влияния Варпа на все расы. Флаг ограничения только по явному событию, не по названию угрозы. Последствия по сюжету; здоровье, деньги и ранг не списывай автоматически.'});}
