import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,actor,applyEvent,clone,ledger,addEvent,replay,messagePath} from '../core.js';
import {resolveJourney,requestCareer,confirmCareer,applyCampaignStory,npcKnowledge,memoryFromVox,activeJourney} from '../campaign.js';
import {serviceFor,visibleMemories} from '../campaign-data.js';
function setup(){const s=initialState();s.navigation.location=s.player.location='А';s.player.affiliation='Астра Милитарум';s.player.rank='Гвардеец';s.squad=[actor({id:'ally',name:'Спутник',location:'А',affiliation:'Астра Милитарум'}),actor({id:'remote',name:'Далёкий',location:'Б',affiliation:'Клан орков'})];s.routes=[{id:'r',name:'А — Б',origin:'А',destination:'Б',mode:'warp',steps:1,risk:'watch',accessGranted:true,transportConfirmed:true,conditionsConfirmed:true,landingRequired:true,landingGranted:false}];return s;}
function apply(s,r){applyEvent(s,{kind:'mechanic',payload:r});return r;}
function plan(s,ids=['ally']){return apply(s,resolveJourney(s,{kind:'journey-plan',routeId:'r',travelerIds:ids},'plan'));}
function depart(s){plan(s);return apply(s,resolveJourney(s,{kind:'journey-depart'},'depart'));}
const chat=[{name:'User',is_user:true,mes:'Прошу перевод'},{name:'Рассказчик',is_user:false,mes:'Командир утвердил перевод. Препятствие устранено.'}],path=messagePath(chat);
test('Service follows affiliation, never race; hive fleet is not navy; no default ship',()=>{const s=setup();assert.equal(s.navigation.ship,null);assert.equal(serviceFor({species:'тау',affiliation:'Клан орков'}).id,'ork');assert.equal(serviceFor({affiliation:'Флот-улей тиранидов'}).id,'hive');assert.equal(serviceFor({species:'космодесантник'}).id,'independent');});
test('Plan grants neither location nor authority; commanding a route needs authority',()=>{const s=setup();assert.throws(()=>resolveJourney(s,{kind:'route-command',routeId:'r'},'cmd'),/Право/);plan(s);assert.equal(s.navigation.location,'А');assert.equal(s.navigation.routeAuthority,false);assert.throws(()=>plan(s),/незавершённый/);});
test('Departure independently checks permission, transport, conditions, location and combat',()=>{for(const flag of ['accessGranted','transportConfirmed','conditionsConfirmed']){const s=setup();s.routes[0][flag]=false;plan(s);assert.throws(()=>resolveJourney(s,{kind:'journey-depart'},'d'));assert.equal(s.navigation.location,'А');}for(const mutate of [s=>s.navigation.location='В',s=>s.battle.active=true]){const s=setup();plan(s);mutate(s);assert.throws(()=>resolveJourney(s,{kind:'journey-depart'},'d'));}});
test('Passenger request does not grant access; departure moves selected travelers and informs only them',()=>{const s=setup();plan(s);apply(s,resolveJourney(s,{kind:'journey-request'},'req'));assert.equal(s.journeys[0].status,'awaiting_access');assert.equal(s.navigation.location,'А');apply(s,resolveJourney(s,{kind:'journey-depart'},'d'));assert.equal(s.player.location,'В пути: А → Б');assert.equal(s.squad[0].location,s.player.location);assert.equal(s.squad[1].location,'Б');assert.equal(s.navigation.routeAuthority,false);assert.equal(visibleMemories(s,'remote').length,0);});
test('Remote companion cannot be teleported into departure',()=>{const s=setup();plan(s,['remote']);assert.throws(()=>resolveJourney(s,{kind:'journey-depart'},'d'),/другом месте/);});
test('Obstacle blocks progress without damage or spawning enemies; resolution resumes the journey',()=>{const s=setup();depart(s);apply(s,resolveJourney(s,{kind:'journey-advance'},'t',()=>5));assert.equal(s.journeys[0].status,'interrupted');assert.equal(s.journeys[0].progress,0);assert.equal(s.player.hp,100);assert.equal(s.enemies.length,0);assert.throws(()=>resolveJourney(s,{kind:'journey-advance'},'t2',()=>90),/препятствия/);s.journeys[0].complication.resolved=true;apply(s,resolveJourney(s,{kind:'journey-advance'},'t2',()=>90));assert.equal(s.journeys[0].status,'ready_to_arrive');});
test('Frozen route governs destination and length; arrival requires landing and never changes rank',()=>{const s=setup();depart(s);assert.throws(()=>resolveJourney(s,{kind:'journey-arrive'},'a'),/этапы/);s.routes[0].destination='В';s.routes[0].steps=99;apply(s,resolveJourney(s,{kind:'journey-advance'},'t',()=>90));assert.throws(()=>resolveJourney(s,{kind:'journey-arrive'},'a'),/посадка/);s.journeys[0].landingGranted=true;apply(s,resolveJourney(s,{kind:'journey-arrive'},'a'));assert.equal(s.navigation.location,'Б');assert.equal(s.player.rank,'Гвардеец');assert.equal(activeJourney(s),undefined);});
test('Cancellation is only before departure; invalid d100 is rejected',()=>{const s=setup();plan(s);apply(s,resolveJourney(s,{kind:'journey-cancel'},'c'));assert.equal(s.navigation.location,'А');const next=setup();depart(next);assert.throws(()=>resolveJourney(next,{kind:'journey-cancel'},'c'),/нельзя отменить/);assert.throws(()=>resolveJourney(next,{kind:'journey-advance'},'t',()=>0),/d100/);});
test('Career request changes no player fields and duplicate pending request is rejected',()=>{const s=setup(),before=clone(s.player);apply(s,requestCareer(s,{type:'promotion',reason:'Отличился',newRank:'Сержант'},'req'));assert.deepEqual(s.player,before);assert.throws(()=>requestCareer(s,{type:'promotion',reason:'Снова'},'r'),/ожидает/);});
test('Promotion needs prior authority scoped to organization, grants no stats or ship',()=>{const s=setup(),event={id:'e',type:'promotion',reason:'Приказ',newRank:'Сержант',authorityId:'ally',knownIds:['player']};assert.throws(()=>confirmCareer(s,event),/Полномочия/);s.squad[0].permissions=['appoint'];applyEvent(s,{kind:'update',payload:confirmCareer(s,event)});assert.equal(s.player.rank,'Сержант');assert.equal(s.navigation.ship,null);assert.equal(s.player.stats.ranged,50);s.squad[1].permissions=['appoint'];assert.throws(()=>confirmCareer(s,{...event,authorityId:'remote'}),/Полномочия/);assert.equal(confirmCareer(s,{...event,authorityId:'remote'},{manual:true}).player.rank,'Сержант');});
test('Hard service excludes ordinary contract release; desertion preserves obligations and local knowledge',()=>{const s=setup();s.player.serviceProfile='custodes';s.player.obligations='Клятва';assert.throws(()=>confirmCareer(s,{id:'e',type:'release',reason:'Устал',exitBasis:'contract'},{manual:true}),/основание/);applyEvent(s,{kind:'update',payload:confirmCareer(s,{id:'e',type:'desertion',reason:'Бежал',knownIds:['player']})});assert.equal(s.player.obligations,'Клятва');assert.equal(s.player.affiliation,'Астра Милитарум');assert.equal(visibleMemories(s,'ally').length,0);});
test('Memory needs real quote; confirmed witnesses learn verbatim, unconfirmed witnesses stay proposals',()=>{const s=setup();s.scene={location:'А',presentIds:['player','ally'],confirmed:true};const u={memories:[{ownerId:'ally',text:'Всем известен секрет',sourceIndex:1,evidence:'Командир утвердил перевод.'},{ownerId:'remote',text:'Перевод',sourceIndex:1,evidence:'Командир утвердил перевод.'},{ownerId:'ally',sourceIndex:1,evidence:'Нет такой цитаты'}]};applyCampaignStory(s,u,chat,path);assert.equal(u.memories.length,2);assert.equal(u.memories[0].confirmed,true);assert.equal(u.memories[0].text,'Командир утвердил перевод.');assert.equal(u.memories[1].confirmed,false);});
test('Current roster cannot approve a memory of an older scene',()=>{const s=setup();s.scene={location:'А',presentIds:['ally'],confirmed:true};const history=[...chat,{name:'Рассказчик',is_user:false,mes:'Другая сцена'}],u={memories:[{ownerId:'ally',sourceIndex:1,evidence:'Командир утвердил перевод.'}]};applyCampaignStory(s,u,history,messagePath(history));assert.equal(u.memories[0].confirmed,false);});
test('NPC knowledge uses own location, confirmed accessible memories, explicitly public news and own channels',()=>{const s=setup();s.memories=[{id:'own',ownerId:'ally',text:'OWN',confirmed:true,sharedWith:[]},{id:'secret',ownerId:'remote',text:'SECRET',confirmed:true,sharedWith:[]},{id:'proposal',ownerId:'ally',text:'PENDING',confirmed:false,sharedWith:[]}];s.feed=[{text:'UNMARKED'},{text:'PUBLIC',public:true}];s.channels=[{id:'a',public:false,participants:['player','ally'],messages:[]},{id:'b',public:false,participants:['remote'],messages:[]}];const known=npcKnowledge(s,'ally');assert.equal(known.location,'А');assert.equal(known.memories.length,1);assert.equal(known.publicFeed.length,1);assert.equal(known.channels.length,1);s.memories[1].sharedWith=['ally'];assert.equal(npcKnowledge(s,'ally').memories.length,2);});
test('Vox memory retains complete message and is private by default',()=>{const m=memoryFromVox({id:'m',from:'Спутник',text:'Полный разговор'},{id:'c',public:false},'ally');assert.equal(m.text,'Спутник: Полный разговор');assert.equal(m.public,false);assert.equal(m.confirmed,true);});
test('Story cannot forge travel progress, new journeys, companion teleportation or unevidenced access changes',()=>{const s=setup();depart(s);const u={journeys:[{id:s.journeys[0].id,status:'arrived',progress:99},{id:'fake',status:'arrived'}],navigation:{location:'В'},player:{location:'В'},squad:[{id:'ally',location:'В'}],routes:[{...s.routes[0],accessGranted:false}]};applyCampaignStory(s,u,chat,path);assert.equal(u.journeys.length,1);assert.equal(u.journeys[0].progress,0);assert.equal(u.journeys[0].status,'underway');assert.equal(u.navigation.location,undefined);assert.equal(u.squad[0].location,'В пути: А → Б');assert.equal(u.routes[0].accessGranted,true);});
test('Latest quote can resolve obstacle without overwriting calculated progress',()=>{const s=setup();depart(s);apply(s,resolveJourney(s,{kind:'journey-advance'},'t',()=>5));const u={journeys:[{id:s.journeys[0].id,status:'arrived',progress:99,complication:{resolved:true},sourceIndex:1,evidence:'Препятствие устранено.'}]};applyCampaignStory(s,u,chat,path);assert.equal(u.journeys[0].complication.resolved,true);assert.equal(u.journeys[0].progress,0);assert.equal(u.journeys[0].status,'interrupted');});
test('Confirmed career event cannot sneak unrelated raw career fields or remote witnesses',()=>{const s=setup();s.squad[0].permissions=['appoint'];apply(s,requestCareer(s,{type:'promotion',reason:'Служба',newRank:'Сержант',authorityId:'ally'},'req'));const u={player:{rank:'Магистр',affiliation:'Клан орков',permissions:['all']},careerEvents:[{...s.careerEvents[0],status:'confirmed',sourceIndex:1,evidence:'Командир утвердил перевод.',knownIds:['remote']}]};applyCampaignStory(s,u,chat,path);assert.equal(u.player.rank,'Сержант');assert.equal(u.player.affiliation,undefined);assert.equal(u.player.permissions,undefined);assert.ok(!u.careerEvents[0].knownIds.includes('remote'));});
test('Editing a branch rolls back journey location and memories together',()=>{const s=setup(),b=ledger();b.base=s;const p=messagePath([{name:'User',is_user:true,mes:'Отправляюсь'}]);addEvent(b,p,'mechanic',resolveJourney(s,{kind:'journey-plan',routeId:'r'},'p'));addEvent(b,p,'mechanic',resolveJourney(replay(b,p),{kind:'journey-depart'},'d'));assert.equal(replay(b,p).navigation.location,'В пути: А → Б');assert.equal(replay(b,p).memories.length,1);const edited=messagePath([{name:'User',is_user:true,mes:'Остаюсь'}]);assert.equal(replay(b,edited).navigation.location,'А');assert.equal(replay(b,edited).memories.length,0);});
test('Story cannot rewrite a final career decision or grant route authority without a source',()=>{const s=setup();s.careerEvents=[{id:'e',type:'promotion',status:'confirmed',reason:'Приказ',newRank:'Гвардеец',knownIds:['player']}];const u={navigation:{routeAuthority:true},careerEvents:[{id:'e',status:'confirmed',newRank:'Магистр',sourceIndex:1,evidence:'Командир утвердил перевод.'}]};applyCampaignStory(s,u,chat,path);assert.equal(u.navigation.routeAuthority,undefined);assert.equal(u.careerEvents[0].newRank,'Гвардеец');});
