import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,actor,validateState,applyEvent,validateUpdate,ledger,addEvent,replay,messagePath,resolveAttack,contextState} from '../core.js';
import {acquireEquipment,returnEquipment,missionBlockers,offerBlockers,resolveMissionAction,applyWorldStory} from '../world.js';
import {blockingThreats,knownThreats} from '../world-data.js';
import {npcKnowledge,journeyBlockers} from '../campaign.js';
const kit={name:'Комплект',tag:'medkit',amount:1};
function setup(){return validateState({...initialState(),player:actor({affiliation:'Астра Милитарум'}),squad:[actor({id:'officer',name:'Командир',affiliation:'Астра Милитарум'})],resources:[{id:'money',name:'Деньги кампании',value:100}],relationships:[{id:'rel',npcId:'officer',trust:30,confirmed:true,npcDebts:['Обязан услугой'],promises:['Дал слово']}],offers:[{id:'o',name:'Комплект',providerId:'officer',method:'purchase',collection:'inventory',item:kit,stock:3,price:10,resourceId:'money',confirmed:true,accessGranted:true,minTrust:20}]});}
function apply(s,r){applyEvent(s,{kind:'mechanic',payload:r});return r;}
test('Legacy state starts with empty social, supply and threat data; optional goals remain optional',()=>{const s=validateState({player:actor()});assert.equal(s.offers.length,0);assert.equal(s.threats.length,0);assert.equal(s.relationships.length,0);assert.equal(validateUpdate({missions:[{id:'m',goals:[{text:'Extra',done:false,required:false}]}]}).missions[0].goals[0].required,false);});
test('Relations are bounded and unconfirmed relations grant neither an offer nor NPC knowledge',()=>{const s=setup();const r=validateUpdate({relationships:[{id:'r',npcId:'officer',trust:999,suspicion:-5,rivalry:120}]}).relationships[0];assert.equal(r.trust,100);assert.equal(r.suspicion,0);assert.equal(r.rivalry,100);s.relationships[0].confirmed=false;assert.ok(offerBlockers(s,s.offers[0]).length);assert.equal(npcKnowledge(s,'officer').relationship,null);});
test('Each NPC receives only their own relationship, known threats and supplier offers',()=>{const s=setup();s.squad.push(actor({id:'other',name:'Другой'}));s.threats=[{id:'t',confirmed:true,public:false,knownIds:['player'],affectedIds:['player'],status:'active'}];assert.equal(npcKnowledge(s,'officer').relationship.npcDebts[0],'Обязан услугой');assert.equal(npcKnowledge(s,'other').relationship,null);assert.equal(npcKnowledge(s,'other').offers.length,0);assert.equal(npcKnowledge(s,'officer').threats.length,0);});
test('Purchase debits exactly configured currency and stock, creates separate item units and a receipt',()=>{const s=setup();const r=acquireEquipment(s,{offerId:'o',quantity:2},'buy');apply(s,r);assert.equal(s.resources[0].value,80);assert.equal(s.offers[0].stock,1);assert.equal(s.inventory.length,2);assert.notEqual(s.inventory[0].id,s.inventory[1].id);assert.equal(s.inventory[0].legalOwner,'player');assert.equal(s.transactions.length,1);assert.equal(s.transactions[0].count,2);});
test('Insufficient money, stock, чужой ресурс, invalid quantity and missing authorization change nothing',()=>{for(const mutate of [s=>s.resources[0].value=1,s=>s.offers[0].stock=0,s=>s.resources[0].ownerId='other',s=>s.offers[0].accessGranted=false,s=>s.offers[0].confirmed=false]){const s=setup();mutate(s);const before=JSON.stringify(s);assert.throws(()=>acquireEquipment(s,{offerId:'o'},'b'));assert.equal(JSON.stringify(s),before);}for(const n of [0,-1,1.2,21,NaN])assert.throws(()=>acquireEquipment(setup(),{offerId:'o',quantity:n},'b'));});
test('Offer access separately checks affiliation, permission, species, place and known trust',()=>{for(const field of ['requiredAffiliation','requiredPermission','location']){const s=setup();s.offers[0][field]='Неподходящее';assert.throws(()=>acquireEquipment(s,{offerId:'o'},'b'));}const s=setup();s.offers[0].allowedSpecies=['некрон'];assert.throws(()=>acquireEquipment(s,{offerId:'o'},'b'));s.offers[0].allowedSpecies=[];s.offers[0].minTrust=40;assert.throws(()=>acquireEquipment(s,{offerId:'o'},'b'));});
test('Gift, trophy and issue do not charge purchase money; issue can preserve organizational ownership',()=>{for(const method of ['gift','trophy','issue']){const s=setup();s.offers[0].method=method;s.offers[0].legalOwner='Полк';apply(s,acquireEquipment(s,{offerId:'o'},'a'));assert.equal(s.resources[0].value,100);assert.equal(s.inventory[0].legalOwner,method==='issue'?'Полк':'player');}});
test('Barter consumes owned stock once and rejects borrowed stock',()=>{const s=setup();s.offers[0].method='barter';s.offers[0].exchangeItemId='scrap';s.offers[0].exchangeAmount=2;s.inventory=[{id:'scrap',name:'Лом',ownerId:'player',amount:3}];apply(s,acquireEquipment(s,{offerId:'o'},'barter'));assert.equal(s.inventory[0].amount,1);assert.equal(s.resources[0].value,100);const other=setup();other.offers[0]={...s.offers[0],stock:3};other.inventory=[{id:'scrap',ownerId:'player',amount:4,loan:true}];assert.throws(()=>acquireEquipment(other,{offerId:'o'},'b'),/собственных/);});
test('Borrowed weapons keep legal owner, are not auto-assigned, return disables use and never refunds',()=>{const s=setup();s.offers[0]={...s.offers[0],method:'loan',collection:'weapons',legalOwner:'Полк',returnCondition:'После миссии',item:{name:'Лазган',mode:'ranged',damage:'2d10+20',penetration:8,ammo:20,cost:1}};apply(s,acquireEquipment(s,{offerId:'o'},'loan'));assert.equal(s.player.weaponIds.length,0);const id=s.weapons[0].id;s.player.weaponIds=[id];s.enemies=[actor({id:'enemy'})];apply(s,returnEquipment(s,{transactionId:s.transactions[0].id},'ret'));assert.equal(s.player.weaponIds.length,0);assert.equal(s.weapons[0].legalOwner,'Полк');assert.equal(s.weapons[0].returned,true);assert.equal(s.offers[0].stock,2);assert.equal(s.resources[0].value,100);s.player.weaponIds=[id];assert.throws(()=>resolveAttack(s,{actorId:'player',targetId:'enemy',weaponId:id},'attack',()=>1),/возвращено/);assert.throws(()=>returnEquipment(s,{transactionId:s.transactions[0].id},'r'));});
test('Return clears only tracked borrowed armor regions, keeps unrelated protection',()=>{const s=setup();s.offers[0]={...s.offers[0],method:'loan',collection:'armor',item:{name:'Броня',protection:10,regions:['chest']}};apply(s,acquireEquipment(s,{offerId:'o'},'loan'));s.player.armor={chest:10,head:15};s.player.armorSources={chest:s.armor[0].id,head:'other'};apply(s,returnEquipment(s,{transactionId:s.transactions[0].id},'r'));assert.equal(s.player.armor.chest,0);assert.equal(s.player.armor.head,15);});
test('Mission dependencies require matching completion or failure and optional named outcome',()=>{const s=setup();s.missions=validateUpdate({missions:[{id:'first',title:'Разведка',status:'active',goals:[]},{id:'next',title:'Штурм',status:'available',goals:[],missionRequirements:[{missionId:'first',status:'completed',outcome:'Данные найдены'}]}]}).missions;assert.throws(()=>resolveMissionAction(s,{kind:'mission-accept',missionId:'next'},'a'));s.missions[0].status='completed';s.missions[0].outcome='Данные потеряны';assert.ok(missionBlockers(s,s.missions[1]).length);s.missions[0].outcome='Данные найдены';apply(s,resolveMissionAction(s,{kind:'mission-accept',missionId:'next'},'a'));assert.equal(s.missions[1].status,'active');const branch={...s.missions[1],missionRequirements:[{missionId:'first',status:'failed'}]};s.missions[0].status='failed';assert.equal(missionBlockers(s,branch).length,0);});
test('Approach selection is an intention, does not complete goals or issue reward',()=>{const s=setup();s.missions=validateUpdate({missions:[{id:'m',title:'Объект',status:'active',goals:[{text:'Добыть данные',done:false}],approaches:[{id:'talk',name:'Переговоры',conditions:'Нужен контакт'},{id:'stealth',name:'Скрытность'}]}]}).missions;apply(s,resolveMissionAction(s,{kind:'mission-approach',missionId:'m',approachId:'stealth'},'a'));assert.equal(s.missions[0].selectedApproachId,'stealth');assert.equal(s.missions[0].goals[0].done,false);assert.equal(s.resources[0].value,100);assert.throws(()=>resolveMissionAction(s,{kind:'mission-approach',missionId:'m',approachId:'fake'},'a'));});
test('Success needs confirmed outcome and all required goals, optional goals can remain undone; failure needs evidence',()=>{const s=setup();s.missions=validateUpdate({missions:[{id:'m',title:'Задание',status:'active',goals:[{text:'Главная',done:false},{text:'Дополнительная',done:false,required:false}]}]}).missions;const a={kind:'mission-resolve',missionId:'m',status:'completed',outcome:'Успех',evidence:'По истории'};assert.throws(()=>resolveMissionAction(s,a,'r'),/подтвердить/);assert.throws(()=>resolveMissionAction(s,a,'r',{reviewed:true}),/цели/);s.missions[0].goals[0].done=true;apply(s,resolveMissionAction(s,a,'r',{reviewed:true}));assert.equal(s.missions[0].status,'completed');assert.equal(s.resources[0].value,100);assert.throws(()=>resolveMissionAction(s,a,'r',{reviewed:true}));});
test('A confirmed active threat can gate travel and supply, but name or severity alone never does',()=>{const s=setup();s.threats=validateUpdate({threats:[{id:'t',name:'Розыск',type:'wanted',status:'active',severity:3,confirmed:true,affectedIds:['player'],knownIds:['player'],blocksTravel:false,blocksAcquisition:false}]}).threats;assert.equal(offerBlockers(s,s.offers[0]).length,0);s.threats[0].blocksAcquisition=true;s.threats[0].blocksTravel=true;assert.ok(offerBlockers(s,s.offers[0]).length);assert.equal(blockingThreats(s,'blocksTravel').length,1);assert.ok(journeyBlockers(s,{origin:s.navigation.location,destination:'Б',accessGranted:true,transportConfirmed:true,conditionsConfirmed:true}).some(x=>x.includes('ограничение')));assert.equal(s.player.hp,100);s.threats[0].status='contained';assert.equal(blockingThreats(s,'blocksTravel').length,0);});
test('Threat scope, affected actor and audience are distinct; resolution can unlock a mission',()=>{const s=setup();s.threats=validateUpdate({threats:[{id:'t',name:'Тревога',confirmed:true,status:'active',affectedIds:['player'],knownIds:['officer'],blocksTravel:true,location:'Другое место'}]}).threats;assert.equal(blockingThreats(s,'blocksTravel').length,0);assert.equal(knownThreats(s,'player').length,0);assert.equal(knownThreats(s,'officer').length,1);s.missions=validateUpdate({missions:[{id:'m',status:'available',resolvedThreatIds:['t']}]}).missions;assert.ok(missionBlockers(s,s.missions[0]).length);s.threats[0].status='resolved';assert.equal(missionBlockers(s,s.missions[0]).length,0);});
test('Story changes need latest real evidence, keep existing confirmed state while proposing changes, and cannot fabricate receipts',()=>{const s=setup(),chat=[{name:'NPC',is_user:false,mes:'Ранее'},{name:'NPC',is_user:false,mes:'Командир доверяет вам после спасения.'}];const u={relationships:[{...s.relationships[0],trust:99}],offers:[{...s.offers[0],stock:99}],threats:[{id:'t',name:'Розыск',confirmed:true,knownIds:['player']}],transactions:[{id:'forged'}]};applyWorldStory(s,u,chat);assert.equal(u.relationships[0].trust,30);assert.equal(u.relationships[0].pending.trust,99);assert.equal(u.offers[0].stock,3);assert.equal(u.threats[0].confirmed,false);assert.equal(u.transactions,undefined);const v={relationships:[{...s.relationships[0],trust:40,sourceIndex:1,evidence:'Командир доверяет вам после спасения.'}]};applyWorldStory(s,v,chat);assert.equal(v.relationships[0].confirmed,true);assert.equal(v.relationships[0].trust,40);});
test('Narrative completion becomes a proposed result rather than unlocking chains prematurely',()=>{const s=setup();s.missions=validateUpdate({missions:[{id:'m',status:'active',goals:[]}]}).missions;const u={missions:[{...s.missions[0],status:'completed',outcome:'Успех',sourceIndex:0,evidence:'Данные доставлены.'}]};applyWorldStory(s,u,[{name:'NPC',is_user:false,mes:'Данные доставлены.'}]);assert.equal(u.missions[0].status,'active');assert.equal(u.missions[0].proposedResolution.confirmed,true);assert.equal(u.missions[0].outcome,undefined);});
test('Context includes only confirmed relationship and offer, and only known threats',()=>{const s=setup();s.relationships[0].confirmed=false;s.offers[0].confirmed=false;s.threats=validateUpdate({threats:[{id:'secret',confirmed:true,knownIds:['officer'],affectedIds:['officer']}]}).threats;const context=contextState(s);assert.equal(context.relationships.length,0);assert.equal(context.offers.length,0);assert.equal(context.threats.length,0);assert.equal(contextState(s,'officer').threats.length,1);});
test('Acquisition replay is idempotent and editing the branch restores currency, stock, items and receipts',()=>{const s=setup(),b=ledger();b.base=s;const chat=[{name:'User',is_user:true,mes:'Покупаю'}],p=messagePath(chat);addEvent(b,p,'mechanic',acquireEquipment(s,{offerId:'o'},'buy'));assert.equal(replay(b,p).resources[0].value,90);assert.equal(replay(b,p).resources[0].value,90);chat[0].mes='Не покупаю';const q=messagePath(chat);assert.equal(replay(b,q).resources[0].value,100);assert.equal(replay(b,q).inventory.length,0);assert.equal(replay(b,q).transactions.length,0);});
